import { 
  IncidentReport, 
  ClusterSummary, 
  ModelMetrics, 
  AdminUser, 
  AuditLogEntry,
  RoadSegmentRisk,
  ModelVersionHistory,
  ConfusionMatrixData,
  FeatureImportanceItem,
  UserAccount,
  HourlyIncidentStat,
  RouteComparisonTelemetry,
  HazardousZoneItem,
  TrendTimePoint,
  AnalyticsTimeRange,
  ContributingFactorItem,
  ReporterDemographicItem,
  IncidentCategoryMaster,
  RiskThresholdConfig,
  DbscanSystemConfig,
  ModeratedContentItem,
  ContentModerationStatus,
  PoliceIntegrationConfig,
  SyncLogEntry,
  ExternalPartnerApiKey,
  FieldMappingRule,
  NotificationTemplate,
  ZoneNotificationSchedule,
  GlobalNotificationSettings,
  PushTestLog,
  SystemJob,
  AStarPerformanceMetrics,
  RouteFeedbackItem,
  DataRetentionPolicy,
  SensitiveDataAccessLog,
  UserConsentMetrics
} from '../../types/superadmin';


export const mockIncidents: IncidentReport[] = [
  {
    id: 'INC-2023-001',
    category: 'Begal',
    coordinates: { lat: -6.200000, lng: 106.816666 },
    locationName: 'Jl. Sudirman, Jakarta Pusat',
    timestamp: '2023-10-27T02:15:00Z',
    status: 'Pending',
    dangerScore: 8,
    description: 'Dua orang mencurigakan membawa senjata tajam.',
    reporterId: 'USR-101'
  },
  {
    id: 'INC-2023-002',
    category: 'Kecelakaan',
    coordinates: { lat: -6.214620, lng: 106.845130 },
    locationName: 'Manggarai, Jakarta Selatan',
    timestamp: '2023-10-27T08:30:00Z',
    status: 'Verified',
    dangerScore: 6,
    description: 'Kecelakaan beruntun melibatkan 3 kendaraan.',
    reporterId: 'USR-102'
  },
  {
    id: 'INC-2023-003',
    category: 'Pelecehan',
    coordinates: { lat: -6.175110, lng: 106.827150 },
    locationName: 'Stasiun Gambir',
    timestamp: '2023-10-27T19:45:00Z',
    status: 'Resolved',
    dangerScore: 7,
    description: 'Tindakan asusila di gerbong kereta.',
    reporterId: 'USR-103'
  },
  {
    id: 'INC-2023-004',
    category: 'Infrastruktur',
    coordinates: { lat: -6.241586, lng: 106.823547 },
    locationName: 'Kuningan, Jakarta Selatan',
    timestamp: '2023-10-26T22:10:00Z',
    status: 'Verified',
    dangerScore: 4,
    description: 'Lampu jalan mati sepanjang 500 meter.',
    reporterId: 'USR-104'
  },
  {
    id: 'INC-2023-005',
    category: 'Lainnya',
    coordinates: { lat: -6.208763, lng: 106.845599 },
    locationName: 'Menteng, Jakarta Pusat',
    timestamp: '2023-10-26T14:20:00Z',
    status: 'Rejected',
    dangerScore: 2,
    description: 'Laporan palsu, tidak ada kejadian.',
    reporterId: 'USR-105'
  },
  {
    id: 'INC-2023-006',
    category: 'Begal',
    coordinates: { lat: -6.220000, lng: 106.820000 },
    locationName: 'Casablanca, Jakarta Selatan',
    timestamp: '2026-09-17T20:30:00.000Z',
    status: 'Pending',
    dangerScore: 9,
    description: 'Tindak kriminal kekerasan.',
    reporterId: 'USR-106'
  },
  {
    id: 'INC-2023-007',
    category: 'Infrastruktur',
    coordinates: { lat: -6.230000, lng: 106.810000 },
    locationName: 'Blok M, Jakarta Selatan',
    timestamp: '2026-09-17T19:30:00.000Z',
    status: 'Pending',
    dangerScore: 5,
    description: 'Jalan berlubang cukup dalam.',
    reporterId: 'USR-107'
  }
];

export const mockClusters: ClusterSummary[] = [
  { id: 'CLS-001', center: { lat: -6.200000, lng: 106.816666 }, incidentCount: 15, radius: 500, dangerLevel: 'Critical' },
  { id: 'CLS-002', center: { lat: -6.214620, lng: 106.845130 }, incidentCount: 8, radius: 300, dangerLevel: 'High' },
  { id: 'CLS-003', center: { lat: -6.175110, lng: 106.827150 }, incidentCount: 3, radius: 200, dangerLevel: 'Medium' }
];

export const mockModelMetrics: ModelMetrics = {
  accuracy: 89.7,
  precision: 85.2,
  recall: 82.5,
  f1Score: 83.8,
  lastTrained: '2023-10-25T10:00:00Z',
  totalTrainingSamples: 15240
};

export const mockUsers: AdminUser[] = [
  { id: 'ADM-001', name: 'Budi Santoso', email: 'budi@jalanaman.id', role: 'Superadmin', status: 'Active' },
  { id: 'ADM-002', name: 'Siti Aminah', email: 'siti@jalanaman.id', role: 'Moderator', status: 'Active' },
  { id: 'ADM-003', name: 'Andi Wijaya', email: 'andi@jalanaman.id', role: 'Analyst', status: 'Suspended' }
];

export const mockAuditLogs: AuditLogEntry[] = [
  { id: 'LOG-001', timestamp: '2023-10-27T08:35:00Z', adminId: 'ADM-002', action: 'Verified Incident', targetId: 'INC-2023-002', details: 'Status changed from Pending to Verified' },
  { id: 'LOG-002', timestamp: '2023-10-26T14:25:00Z', adminId: 'ADM-001', action: 'Rejected Incident', targetId: 'INC-2023-005', details: 'Marked as false report' },
  { id: 'LOG-003', timestamp: '2023-10-25T10:05:00Z', adminId: 'ADM-001', action: 'Model Retrained', details: 'Triggered manual retraining of Risk Model' }
];

// Data for charts (5W1H Logic)
export const chartDataCategory = [
  { name: 'Begal', value: 45 },
  { name: 'Pelecehan', value: 30 },
  { name: 'Kecelakaan', value: 20 },
  { name: 'Infrastruktur', value: 15 },
  { name: 'Lainnya', value: 5 },
];

export const chartDataTime = [
  { time: '00:00', incidents: 12 },
  { time: '04:00', incidents: 8 },
  { time: '08:00', incidents: 25 },
  { time: '12:00', incidents: 15 },
  { time: '16:00', incidents: 30 },
  { time: '20:00', incidents: 40 },
];

export const chartDataRegion = [
  { name: 'Jaksel', value: 120 },
  { name: 'Jakpus', value: 80 },
  { name: 'Jakbar', value: 65 },
  { name: 'Jaktim', value: 90 },
  { name: 'Jakut', value: 45 },
];

export const chartDataResolution = [
  { month: 'Jan', verified: 40, rejected: 10 },
  { month: 'Feb', verified: 50, rejected: 15 },
  { month: 'Mar', verified: 45, rejected: 12 },
  { month: 'Apr', verified: 60, rejected: 20 },
  { month: 'May', verified: 75, rejected: 8 },
];

export const chartDataDemographic = [
  { trustScore: 'Tinggi', users: 1500 },
  { trustScore: 'Sedang', users: 800 },
  { trustScore: 'Rendah', users: 200 },
];

// Top 3 Hotspots
export const topHotspots = [
  { id: 1, name: 'Jl. Margonda Raya', area: 'Depok', newIncidents: 12, trend: 'up' },
  { id: 2, name: 'Stasiun Manggarai', area: 'Jakarta Selatan', newIncidents: 8, trend: 'up' },
  { id: 3, name: 'Kawasan Monas', area: 'Jakarta Pusat', newIncidents: 5, trend: 'down' },
];

// System Health
export const systemHealth = [
  { id: 'dbscan', name: 'DBSCAN Engine', status: 'Healthy', latency: '12ms', lastSync: '1 min ago' },
  { id: 'rf', name: 'Random Forest API', status: 'Healthy', latency: '45ms', lastSync: '1 min ago' },
  { id: 'maps', name: 'Mapbox Services', status: 'Warning', latency: '150ms', lastSync: '5 mins ago' },
];

export const chartDataModel = [
  { metric: 'Accuracy', value: 89.7, benchmark: 80 },
  { metric: 'Precision', value: 85.2, benchmark: 80 },
  { metric: 'Recall', value: 82.5, benchmark: 80 },
  { metric: 'F1-Score', value: 83.8, benchmark: 80 },
  { metric: 'AUC-ROC', value: 91.2, benchmark: 85 },
];

export const chartDataWeekly = [
  { week: 'W1', pending: 15, verified: 45, rejected: 10 },
  { week: 'W2', pending: 20, verified: 55, rejected: 12 },
  { week: 'W3', pending: 12, verified: 60, rejected: 8 },
  { week: 'W4', pending: 25, verified: 40, rejected: 15 },
];

export const mockRoadSegments: RoadSegmentRisk[] = [
  {
    id: 'SEG-001',
    name: 'Jl. Layang Non-Tol Casablanca (Flyover)',
    region: 'Jakarta Selatan',
    riskScore: 88,
    dangerLevel: 'Kritis',
    peakDangerHours: '00.00 - 04.30 WIB',
    lightingQuality: 'Minim',
    incidentHistoryCount: 19,
    policePostDistance: 1200,
    lastEvaluated: '15 Menit yang lalu',
    featureContributions: {
      crimeHistory: 44,
      lighting: 28,
      nightTime: 18,
      securityProximity: 10,
    },
  },
  {
    id: 'SEG-002',
    name: 'Jl. TB Simatupang (Flyover Pasar Rebo)',
    region: 'Jakarta Timur',
    riskScore: 79,
    dangerLevel: 'Rawan',
    peakDangerHours: '23.30 - 04.00 WIB',
    lightingQuality: 'Sedang',
    incidentHistoryCount: 14,
    policePostDistance: 850,
    lastEvaluated: '30 Menit yang lalu',
    featureContributions: {
      crimeHistory: 38,
      lighting: 24,
      nightTime: 22,
      securityProximity: 16,
    },
  },
  {
    id: 'SEG-003',
    name: 'Jl. Margonda Raya (Pocut Meurah Segmen)',
    region: 'Depok',
    riskScore: 74,
    dangerLevel: 'Rawan',
    peakDangerHours: '01.00 - 04.30 WIB',
    lightingQuality: 'Sedang',
    incidentHistoryCount: 12,
    policePostDistance: 920,
    lastEvaluated: '1 Jam yang lalu',
    featureContributions: {
      crimeHistory: 36,
      lighting: 26,
      nightTime: 20,
      securityProximity: 18,
    },
  },
  {
    id: 'SEG-004',
    name: 'Jl. Manggarai Utara (Underpass Kereta)',
    region: 'Jakarta Selatan',
    riskScore: 68,
    dangerLevel: 'Rawan',
    peakDangerHours: '22.00 - 03.30 WIB',
    lightingQuality: 'Minim',
    incidentHistoryCount: 11,
    policePostDistance: 400,
    lastEvaluated: '45 Menit yang lalu',
    featureContributions: {
      crimeHistory: 34,
      lighting: 32,
      nightTime: 20,
      securityProximity: 14,
    },
  },
  {
    id: 'SEG-005',
    name: 'Jl. KH Noer Ali (Kalimalang Caman)',
    region: 'Bekasi',
    riskScore: 62,
    dangerLevel: 'Waspada',
    peakDangerHours: '00.30 - 04.30 WIB',
    lightingQuality: 'Minim',
    incidentHistoryCount: 9,
    policePostDistance: 1400,
    lastEvaluated: '2 Jam yang lalu',
    featureContributions: {
      crimeHistory: 30,
      lighting: 34,
      nightTime: 18,
      securityProximity: 18,
    },
  },
  {
    id: 'SEG-006',
    name: 'Jl. Daan Mogot Km 14 (Pesing)',
    region: 'Jakarta Barat',
    riskScore: 58,
    dangerLevel: 'Waspada',
    peakDangerHours: '23.00 - 03.00 WIB',
    lightingQuality: 'Sedang',
    incidentHistoryCount: 8,
    policePostDistance: 650,
    lastEvaluated: '3 Jam yang lalu',
    featureContributions: {
      crimeHistory: 28,
      lighting: 28,
      nightTime: 24,
      securityProximity: 20,
    },
  },
  {
    id: 'SEG-007',
    name: 'Jl. RE Martadinata (Ancol Selatan)',
    region: 'Jakarta Utara',
    riskScore: 52,
    dangerLevel: 'Waspada',
    peakDangerHours: '01.00 - 04.00 WIB',
    lightingQuality: 'Minim',
    incidentHistoryCount: 7,
    policePostDistance: 1100,
    lastEvaluated: '3 Jam yang lalu',
    featureContributions: {
      crimeHistory: 26,
      lighting: 36,
      nightTime: 22,
      securityProximity: 16,
    },
  },
  {
    id: 'SEG-008',
    name: 'Jl. MH Thamrin (Bundaran HI Koridor)',
    region: 'Jakarta Pusat',
    riskScore: 18,
    dangerLevel: 'Aman',
    peakDangerHours: '02.00 - 03.00 WIB',
    lightingQuality: 'Terang',
    incidentHistoryCount: 1,
    policePostDistance: 150,
    lastEvaluated: '10 Menit yang lalu',
    featureContributions: {
      crimeHistory: 10,
      lighting: 10,
      nightTime: 30,
      securityProximity: 50,
    },
  },
  {
    id: 'SEG-009',
    name: 'Jl. Jend. Sudirman (SCBD Semanggi)',
    region: 'Jakarta Selatan',
    riskScore: 22,
    dangerLevel: 'Aman',
    peakDangerHours: '01.30 - 03.00 WIB',
    lightingQuality: 'Terang',
    incidentHistoryCount: 2,
    policePostDistance: 250,
    lastEvaluated: '20 Menit yang lalu',
    featureContributions: {
      crimeHistory: 12,
      lighting: 12,
      nightTime: 28,
      securityProximity: 48,
    },
  },
  {
    id: 'SEG-010',
    name: 'Jl. HR Rasuna Said (Kuningan Sentra)',
    region: 'Jakarta Selatan',
    riskScore: 27,
    dangerLevel: 'Aman',
    peakDangerHours: '01.00 - 03.30 WIB',
    lightingQuality: 'Terang',
    incidentHistoryCount: 3,
    policePostDistance: 320,
    lastEvaluated: '1 Jam yang lalu',
    featureContributions: {
      crimeHistory: 15,
      lighting: 15,
      nightTime: 25,
      securityProximity: 45,
    },
  },
];

export const mockFeatureImportance: FeatureImportanceItem[] = [
  {
    feature: 'Riwayat Kepadatan Kriminalitas (DBSCAN Cluster Weight)',
    importance: 38.5,
    category: 'Kriminalitas',
    description: 'Frekuensi kejadian begal, curas, dan pelecehan dalam radius 500m dalam 6 bulan terakhir.',
  },
  {
    feature: 'Indeks Kualitas Penerangan Jalan (Lux & Lampu Aktif)',
    importance: 27.8,
    category: 'Infrastruktur',
    description: 'Rasio lampu jalan menyala dan tingkat visibilitas pengendara di malam hari.',
  },
  {
    feature: 'Variabel Spatiotemporal Dini Hari (00.00 - 05.00 WIB)',
    importance: 19.4,
    category: 'Spatiotemporal',
    description: 'Pengali risiko berbasis jam biologis sunyi dan penurunan patroli reguler.',
  },
  {
    feature: 'Jarak Geodesik ke Pos Polisi / Patroli Siaga',
    importance: 14.3,
    category: 'Lingkungan',
    description: 'Kedekatan titik segmen dengan pos keamanan aktif untuk percepatan respon SOS.',
  },
];

export const mockConfusionMatrix: ConfusionMatrixData = {
  truePositive: 1240,
  falsePositive: 94,
  falseNegative: 38,
  trueNegative: 4820,
};

export const mockModelHistory: ModelVersionHistory[] = [
  {
    version: 'v2.4.2',
    trainedAt: '2026-09-17T12:30:00Z',
    durationSeconds: 45,
    datasetScope: 'Semua Data (12 Bulan)',
    sampleCount: 24800,
    accuracy: 91.4,
    f1Score: 87.4,
    aucRoc: 0.942,
    status: 'Active',
    trainedBy: 'Superadmin Pipeline Agent',
    notes: 'Penambahan dataset crowdsourcing terverifikasi Q3 & tuning n_estimators=250.',
  },
  {
    version: 'v2.4.1',
    trainedAt: '2026-09-10T08:15:00Z',
    durationSeconds: 42,
    datasetScope: '6 Bulan Terakhir',
    sampleCount: 18500,
    accuracy: 89.7,
    f1Score: 85.1,
    aucRoc: 0.918,
    status: 'Deprecated',
    trainedBy: 'Superadmin Pipeline Agent',
    notes: 'Kalibrasi bobot zona perbatasan Depok & Jakarta Selatan.',
  },
  {
    version: 'v2.4.0',
    trainedAt: '2026-08-25T14:00:00Z',
    durationSeconds: 38,
    datasetScope: '3 Bulan Terakhir',
    sampleCount: 12200,
    accuracy: 88.2,
    f1Score: 83.6,
    aucRoc: 0.902,
    status: 'Archived',
    trainedBy: 'Budi Santoso (Admin)',
    notes: 'Integrasi awal data historis Ditreskrimum Polda Metro Jaya 2024.',
  },
  {
    version: 'v2.3.9',
    trainedAt: '2026-08-01T09:20:00Z',
    durationSeconds: 40,
    datasetScope: 'Semua Data',
    sampleCount: 15400,
    accuracy: 86.8,
    f1Score: 81.9,
    aucRoc: 0.887,
    status: 'Archived',
    trainedBy: 'Budi Santoso (Admin)',
    notes: 'Model baseline kompetisi ICONFEST 2026.',
  },
];

export const mockUserAccounts: UserAccount[] = [
  {
    id: 'USR-101',
    name: 'Budi Santoso',
    email: 'budi.santoso@jalanaman.id',
    phone: '+62 812-8890-1122',
    role: 'Superadmin',
    status: 'Active',
    reportCount: 24,
    verifiedReportCount: 24,
    rejectedReportCount: 0,
    trustScore: 99,
    dominantRegion: 'Jakarta Pusat',
    joinedAt: '2026-01-10T08:00:00Z',
    lastActive: '5 Menit yang lalu',
    routeSearches: [
      { id: 'SRC-01', origin: 'Monas Sentral', destination: 'Kebayoran Baru', chosenRoute: 'Aman', estimatedDurationMin: 22, timestamp: '2026-09-17T18:40:00Z' },
      { id: 'SRC-02', origin: 'Bundaran HI', destination: 'Kuningan Timur', chosenRoute: 'Aman', estimatedDurationMin: 15, timestamp: '2026-09-16T22:15:00Z' },
      { id: 'SRC-03', origin: 'Menteng', destination: 'Tebet Eco Park', chosenRoute: 'Tercepat', estimatedDurationMin: 19, timestamp: '2026-09-15T20:30:00Z' },
    ],
    routeRatings: [
      { id: 'RAT-01', routeName: 'Koridor Utama Sudirman - Thamrin', rating: 5, safetyConfirmed: true, comment: 'Penerangan sangat maksimal dan pos polisi selalu siaga.', timestamp: '2026-09-16T23:00:00Z' },
      { id: 'RAT-02', routeName: 'Jalur Arteri Rasuna Said Bypass', rating: 5, safetyConfirmed: true, comment: 'Rute aman dan minim titik blindspot.', timestamp: '2026-09-14T21:45:00Z' },
    ],
    incidentReports: [
      { id: 'INC-101-1', category: 'Infrastruktur', location: 'Jl. Sudirman Dekat Halte Dukuh Atas', timestamp: '2026-09-12T01:30:00Z', status: 'Verified' },
      { id: 'INC-101-2', category: 'Infrastruktur', location: 'Jl. Imam Bonjol No. 42', timestamp: '2026-08-20T23:10:00Z', status: 'Verified' },
    ],
  },
  {
    id: 'USR-102',
    name: 'Siti Aminah',
    email: 'siti.aminah@jalanaman.id',
    phone: '+62 813-7744-9911',
    role: 'Moderator',
    status: 'Active',
    reportCount: 19,
    verifiedReportCount: 18,
    rejectedReportCount: 1,
    trustScore: 95,
    dominantRegion: 'Jakarta Selatan',
    joinedAt: '2026-02-14T09:30:00Z',
    lastActive: '12 Menit yang lalu',
    routeSearches: [
      { id: 'SRC-04', origin: 'Blok M Square', destination: 'Pancoran Riverside', chosenRoute: 'Aman', estimatedDurationMin: 20, timestamp: '2026-09-17T20:10:00Z' },
      { id: 'SRC-05', origin: 'Fatmawati Raya', destination: 'SCBD Lot 8', chosenRoute: 'Aman', estimatedDurationMin: 25, timestamp: '2026-09-16T00:45:00Z' },
    ],
    routeRatings: [
      { id: 'RAT-03', routeName: 'Jalur Arteri Wolter Monginsidi', rating: 4, safetyConfirmed: true, comment: 'Lampu jalan terang, cukup ramai pengendara motor.', timestamp: '2026-09-16T01:20:00Z' },
    ],
    incidentReports: [
      { id: 'INC-102-1', category: 'Begal', location: 'Casablanca Dekat Terowongan', timestamp: '2026-09-10T02:15:00Z', status: 'Verified' },
      { id: 'INC-102-2', category: 'Kecelakaan', location: 'Underpass Mampang Menuju Kuningan', timestamp: '2026-08-28T04:00:00Z', status: 'Verified' },
    ],
  },
  {
    id: 'USR-103',
    name: 'Ahmad Fauzi',
    email: 'ahmad.fauzi@gmail.com',
    phone: '+62 856-1122-3344',
    role: 'User',
    status: 'Active',
    reportCount: 14,
    verifiedReportCount: 13,
    rejectedReportCount: 1,
    trustScore: 92,
    dominantRegion: 'Depok',
    joinedAt: '2026-03-01T11:00:00Z',
    lastActive: '25 Menit yang lalu',
    routeSearches: [
      { id: 'SRC-06', origin: 'Margonda UI', destination: 'Sawangan Permai', chosenRoute: 'Aman', estimatedDurationMin: 28, timestamp: '2026-09-17T22:00:00Z' },
      { id: 'SRC-07', origin: 'Kelapa Dua Brimob', destination: 'Kukusan Teknik', chosenRoute: 'Aman', estimatedDurationMin: 14, timestamp: '2026-09-15T23:10:00Z' },
    ],
    routeRatings: [
      { id: 'RAT-04', routeName: 'Koridor Margonda - Juanda Depok', rating: 5, safetyConfirmed: true, comment: 'Sangat aman, dipandu lewat jalan raya bukan gang sepi.', timestamp: '2026-09-16T00:15:00Z' },
    ],
    incidentReports: [
      { id: 'INC-103-1', category: 'Pelecehan', location: 'JPO Margonda Dekat Detos', timestamp: '2026-09-08T21:40:00Z', status: 'Verified' },
      { id: 'INC-103-2', category: 'Infrastruktur', location: 'Jl. Akses UI Lampu Mati', timestamp: '2026-08-15T23:30:00Z', status: 'Verified' },
    ],
  },
  {
    id: 'USR-104',
    name: 'Dewi Lestari',
    email: 'dewi.lestari@yahoo.com',
    phone: '+62 878-2233-4455',
    role: 'User',
    status: 'Active',
    reportCount: 10,
    verifiedReportCount: 9,
    rejectedReportCount: 1,
    trustScore: 89,
    dominantRegion: 'Jakarta Timur',
    joinedAt: '2026-03-15T14:20:00Z',
    lastActive: '1 Jam yang lalu',
    routeSearches: [
      { id: 'SRC-08', origin: 'Pusat Grosir Cililitan', destination: 'Pasar Rebo Flyover', chosenRoute: 'Aman', estimatedDurationMin: 16, timestamp: '2026-09-17T01:30:00Z' },
    ],
    routeRatings: [
      { id: 'RAT-05', routeName: 'Jl. Raya Bogor Segmen Kramat Jati', rating: 4, safetyConfirmed: true, comment: 'Rute memutar sedikit tapi jalanan ramai martabak dan warung buka.', timestamp: '2026-09-17T02:00:00Z' },
    ],
    incidentReports: [
      { id: 'INC-104-1', category: 'Begal', location: 'Flyover TB Simatupang Menuju Ciracas', timestamp: '2026-09-02T02:45:00Z', status: 'Verified' },
    ],
  },
  {
    id: 'USR-105',
    name: 'Rizky Pratama',
    email: 'rizky.pratama@gmail.com',
    phone: '+62 811-9988-7766',
    role: 'User',
    status: 'Active',
    reportCount: 8,
    verifiedReportCount: 6,
    rejectedReportCount: 2,
    trustScore: 75,
    dominantRegion: 'Bekasi',
    joinedAt: '2026-04-10T10:15:00Z',
    lastActive: '3 Jam yang lalu',
    routeSearches: [
      { id: 'SRC-09', origin: 'Summarecon Mall Bekasi', destination: 'Kalimalang Caman', chosenRoute: 'Aman', estimatedDurationMin: 24, timestamp: '2026-09-16T21:00:00Z' },
    ],
    routeRatings: [
      { id: 'RAT-06', routeName: 'Kalimalang Sisi Selatan', rating: 3, safetyConfirmed: false, comment: 'Lampu jalan beberapa titik redup, butuh kehati-hatian ekstra.', timestamp: '2026-09-16T21:40:00Z' },
    ],
    incidentReports: [
      { id: 'INC-105-1', category: 'Infrastruktur', location: 'Jl. KH Noer Ali Caman Lampu Padam', timestamp: '2026-08-30T00:20:00Z', status: 'Verified' },
      { id: 'INC-105-2', category: 'Lainnya', location: 'Kranji Rel Kereta', timestamp: '2026-08-10T19:00:00Z', status: 'Rejected' },
    ],
  },
  {
    id: 'USR-106',
    name: 'Hendro Wicaksono',
    email: 'hendro.w@outlook.com',
    phone: '+62 812-3344-5566',
    role: 'User',
    status: 'Suspended',
    statusReason: 'Terlalu sering melaporkan insiden palsu / hoax tanpa bukti faktual (3 kali ditolak berturut-turut).',
    reportCount: 10,
    verifiedReportCount: 3,
    rejectedReportCount: 7,
    trustScore: 30,
    dominantRegion: 'Jakarta Barat',
    joinedAt: '2026-05-02T16:40:00Z',
    lastActive: '2 Hari yang lalu',
    routeSearches: [
      { id: 'SRC-10', origin: 'Pesing Daan Mogot', destination: 'Cengkareng Timur', chosenRoute: 'Tercepat', estimatedDurationMin: 18, timestamp: '2026-09-14T02:00:00Z' },
    ],
    routeRatings: [],
    incidentReports: [
      { id: 'INC-106-1', category: 'Begal', location: 'Daan Mogot Km 14 Pesing', timestamp: '2026-09-12T02:10:00Z', status: 'Rejected' },
      { id: 'INC-106-2', category: 'Begal', location: 'Jembatan Gantung Cengkareng', timestamp: '2026-09-11T03:00:00Z', status: 'Rejected' },
    ],
  },
  {
    id: 'USR-107',
    name: 'Dimas Anggara',
    email: 'dimas.ang@tempmail.com',
    phone: '+62 899-4455-6677',
    role: 'User',
    status: 'Banned',
    statusReason: 'Penyalahgunaan API untuk spamming koordinat palsu secara otomatis (skrip bot terdeteksi).',
    reportCount: 22,
    verifiedReportCount: 1,
    rejectedReportCount: 21,
    trustScore: 5,
    dominantRegion: 'Jakarta Utara',
    joinedAt: '2026-06-12T09:00:00Z',
    lastActive: '1 Minggu yang lalu',
    routeSearches: [],
    routeRatings: [],
    incidentReports: [
      { id: 'INC-107-1', category: 'Begal', location: 'RE Martadinata Ancol Selatan', timestamp: '2026-09-05T01:00:00Z', status: 'Rejected' },
      { id: 'INC-107-2', category: 'Begal', location: 'Tanjung Priok Pos 9', timestamp: '2026-09-05T01:02:00Z', status: 'Rejected' },
    ],
  },
  {
    id: 'USR-108',
    name: 'Putri Rahayu',
    email: 'putri.rahayu@jalanaman.id',
    phone: '+62 812-5566-7788',
    role: 'Moderator',
    status: 'Active',
    reportCount: 16,
    verifiedReportCount: 15,
    rejectedReportCount: 1,
    trustScore: 94,
    dominantRegion: 'Tangerang',
    joinedAt: '2026-02-20T10:00:00Z',
    lastActive: '40 Menit yang lalu',
    routeSearches: [
      { id: 'SRC-11', origin: 'BSD Junction', destination: 'Bintaro Jaya Sektor 9', chosenRoute: 'Aman', estimatedDurationMin: 17, timestamp: '2026-09-17T19:30:00Z' },
    ],
    routeRatings: [
      { id: 'RAT-07', routeName: 'Jalur Boulevard BSD Raya Utama', rating: 5, safetyConfirmed: true, comment: 'Sangat aman dan penerangan jalan kelas satu.', timestamp: '2026-09-17T20:00:00Z' },
    ],
    incidentReports: [
      { id: 'INC-108-1', category: 'Infrastruktur', location: 'Jl. Pahlawan Seribu BSD Lampu Padam', timestamp: '2026-09-09T22:30:00Z', status: 'Verified' },
    ],
  },
  {
    id: 'USR-109',
    name: 'Kevin Sanjaya',
    email: 'kevin.sanjaya@gmail.com',
    phone: '+62 817-8899-0011',
    role: 'User',
    status: 'Active',
    reportCount: 7,
    verifiedReportCount: 6,
    rejectedReportCount: 1,
    trustScore: 86,
    dominantRegion: 'Jakarta Selatan',
    joinedAt: '2026-04-25T13:40:00Z',
    lastActive: '2 Jam yang lalu',
    routeSearches: [
      { id: 'SRC-12', origin: 'Senopati Senayan', destination: 'Kemang Timur Raya', chosenRoute: 'Aman', estimatedDurationMin: 15, timestamp: '2026-09-16T23:50:00Z' },
    ],
    routeRatings: [
      { id: 'RAT-08', routeName: 'Antasari Bawah Koridor', rating: 4, safetyConfirmed: true, comment: 'Lalu lintas malam lancar dan aman.', timestamp: '2026-09-17T00:20:00Z' },
    ],
    incidentReports: [
      { id: 'INC-109-1', category: 'Pelecehan', location: 'Jalan Kemang Raya Dekat Cafe', timestamp: '2026-08-22T01:10:00Z', status: 'Verified' },
    ],
  },
  {
    id: 'USR-110',
    name: 'Anisa Nuraini',
    email: 'anisa.nuraini@gmail.com',
    phone: '+62 852-6677-8899',
    role: 'User',
    status: 'Active',
    reportCount: 11,
    verifiedReportCount: 10,
    rejectedReportCount: 1,
    trustScore: 91,
    dominantRegion: 'Jakarta Pusat',
    joinedAt: '2026-03-20T15:10:00Z',
    lastActive: '15 Menit yang lalu',
    routeSearches: [
      { id: 'SRC-13', origin: 'Stasiun Gambir', destination: 'Salemba Raya', chosenRoute: 'Aman', estimatedDurationMin: 12, timestamp: '2026-09-17T21:10:00Z' },
    ],
    routeRatings: [
      { id: 'RAT-09', routeName: 'Kramat Raya Jalur Aman', rating: 5, safetyConfirmed: true, comment: 'Banyak polisi patroli dan dekat RS Carolus.', timestamp: '2026-09-17T21:40:00Z' },
    ],
    incidentReports: [
      { id: 'INC-110-1', category: 'Infrastruktur', location: 'Underpass Senen Arah Galur', timestamp: '2026-09-01T23:00:00Z', status: 'Verified' },
    ],
  },
];

// ==========================================
// 5. ANALYTICS & STATISTIK DATASETS
// ==========================================

export const mockHourlyDistribution: HourlyIncidentStat[] = [
  { hour: '00:00', hourNumber: 0, total: 32, begal: 19, pelecehan: 7, kecelakaan: 4, infrastruktur: 2, isPeakDanger: true },
  { hour: '01:00', hourNumber: 1, total: 44, begal: 28, pelecehan: 9, kecelakaan: 5, infrastruktur: 2, isPeakDanger: true },
  { hour: '02:00', hourNumber: 2, total: 52, begal: 35, pelecehan: 11, kecelakaan: 4, infrastruktur: 2, isPeakDanger: true },
  { hour: '03:00', hourNumber: 3, total: 46, begal: 31, pelecehan: 9, kecelakaan: 4, infrastruktur: 2, isPeakDanger: true },
  { hour: '04:00', hourNumber: 4, total: 29, begal: 18, pelecehan: 5, kecelakaan: 4, infrastruktur: 2, isPeakDanger: true },
  { hour: '05:00', hourNumber: 5, total: 16, begal: 7, pelecehan: 4, kecelakaan: 3, infrastruktur: 2, isPeakDanger: false },
  { hour: '06:00', hourNumber: 6, total: 12, begal: 2, pelecehan: 3, kecelakaan: 5, infrastruktur: 2, isPeakDanger: false },
  { hour: '07:00', hourNumber: 7, total: 19, begal: 2, pelecehan: 5, kecelakaan: 9, infrastruktur: 3, isPeakDanger: false },
  { hour: '08:00', hourNumber: 8, total: 24, begal: 3, pelecehan: 6, kecelakaan: 11, infrastruktur: 4, isPeakDanger: false },
  { hour: '09:00', hourNumber: 9, total: 15, begal: 2, pelecehan: 3, kecelakaan: 6, infrastruktur: 4, isPeakDanger: false },
  { hour: '10:00', hourNumber: 10, total: 14, begal: 1, pelecehan: 3, kecelakaan: 6, infrastruktur: 4, isPeakDanger: false },
  { hour: '11:00', hourNumber: 11, total: 13, begal: 1, pelecehan: 2, kecelakaan: 6, infrastruktur: 4, isPeakDanger: false },
  { hour: '12:00', hourNumber: 12, total: 18, begal: 2, pelecehan: 4, kecelakaan: 8, infrastruktur: 4, isPeakDanger: false },
  { hour: '13:00', hourNumber: 13, total: 16, begal: 2, pelecehan: 3, kecelakaan: 7, infrastruktur: 4, isPeakDanger: false },
  { hour: '14:00', hourNumber: 14, total: 17, begal: 3, pelecehan: 4, kecelakaan: 6, infrastruktur: 4, isPeakDanger: false },
  { hour: '15:00', hourNumber: 15, total: 22, begal: 4, pelecehan: 5, kecelakaan: 9, infrastruktur: 4, isPeakDanger: false },
  { hour: '16:00', hourNumber: 16, total: 27, begal: 5, pelecehan: 7, kecelakaan: 11, infrastruktur: 4, isPeakDanger: false },
  { hour: '17:00', hourNumber: 17, total: 34, begal: 6, pelecehan: 11, kecelakaan: 13, infrastruktur: 4, isPeakDanger: false },
  { hour: '18:00', hourNumber: 18, total: 38, begal: 9, pelecehan: 13, kecelakaan: 12, infrastruktur: 4, isPeakDanger: false },
  { hour: '19:00', hourNumber: 19, total: 35, begal: 11, pelecehan: 10, kecelakaan: 10, infrastruktur: 4, isPeakDanger: false },
  { hour: '20:00', hourNumber: 20, total: 33, begal: 13, pelecehan: 8, kecelakaan: 8, infrastruktur: 4, isPeakDanger: false },
  { hour: '21:00', hourNumber: 21, total: 30, begal: 14, pelecehan: 7, kecelakaan: 6, infrastruktur: 3, isPeakDanger: false },
  { hour: '22:00', hourNumber: 22, total: 36, begal: 19, pelecehan: 8, kecelakaan: 6, infrastruktur: 3, isPeakDanger: false },
  { hour: '23:00', hourNumber: 23, total: 41, begal: 24, pelecehan: 9, kecelakaan: 5, infrastruktur: 3, isPeakDanger: true },
];

export const mockRouteComparisonData: RouteComparisonTelemetry = {
  totalSearches: 48620,
  safeRouteCount: 37340,
  safeRoutePct: 76.8,
  fastestRouteCount: 11280,
  fastestRoutePct: 23.2,
  avgTimeDifferenceMinutes: 3.8,
  avgHazardsAvoidedCount: 2.4,
  citizenSatisfactionSafe: 4.84,
  citizenSatisfactionFastest: 3.91,
  safetyConfirmationRate: 94.6,
  monthlyTrends: [
    { month: 'Apr', safePct: 62.4, fastestPct: 37.6, avgTimeDiffMin: 4.2, totalSearches: 5400 },
    { month: 'Mei', safePct: 66.8, fastestPct: 33.2, avgTimeDiffMin: 4.0, totalSearches: 6800 },
    { month: 'Jun', safePct: 70.1, fastestPct: 29.9, avgTimeDiffMin: 3.9, totalSearches: 8100 },
    { month: 'Jul', safePct: 73.5, fastestPct: 26.5, avgTimeDiffMin: 3.8, totalSearches: 9200 },
    { month: 'Agt', safePct: 75.2, fastestPct: 24.8, avgTimeDiffMin: 3.7, totalSearches: 10400 },
    { month: 'Sep', safePct: 76.8, fastestPct: 23.2, avgTimeDiffMin: 3.8, totalSearches: 8720 },
  ],
};

export const mockHazardousZones: HazardousZoneItem[] = [
  {
    rank: 1,
    id: 'ZONE-01',
    name: 'Jl. Layang Non-Tol Casablanca (Flyover)',
    region: 'Jakarta Selatan',
    city: 'DKI Jakarta',
    coordinates: { lat: -6.220000, lng: 106.820000 },
    incidentCount: 24,
    riskScore: 88,
    dangerLevel: 'Kritis',
    dominantCategory: 'Begal',
    peakHours: '00.00 - 04.30 WIB',
    trend: 'up',
    trendPercent: 15.2,
    policeDistanceMeters: 1200,
    lightingStatus: 'Minim',
    recommendedIntervention: 'Patroli Mobile Ditlantas & Instalasi Kamera AI Spatiotemporal',
  },
  {
    rank: 2,
    id: 'ZONE-02',
    name: 'Jl. TB Simatupang (Flyover Pasar Rebo)',
    region: 'Jakarta Timur',
    city: 'DKI Jakarta',
    coordinates: { lat: -6.3045, lng: 106.8672 },
    incidentCount: 19,
    riskScore: 82,
    dangerLevel: 'Kritis',
    dominantCategory: 'Begal',
    peakHours: '23.30 - 04.00 WIB',
    trend: 'up',
    trendPercent: 8.4,
    policeDistanceMeters: 850,
    lightingStatus: 'Sedang',
    recommendedIntervention: 'Penambahan Titik PJU LED & Pos Sabhara Siaga Malam',
  },
  {
    rank: 3,
    id: 'ZONE-03',
    name: 'Jl. Margonda Raya (Segmen Juanda - Pocut Meurah)',
    region: 'Depok',
    city: 'Jawa Barat',
    coordinates: { lat: -6.3725, lng: 106.8322 },
    incidentCount: 17,
    riskScore: 76,
    dangerLevel: 'Rawan',
    dominantCategory: 'Begal',
    peakHours: '01.00 - 04.30 WIB',
    trend: 'stable',
    trendPercent: 0.8,
    policeDistanceMeters: 920,
    lightingStatus: 'Sedang',
    recommendedIntervention: 'Operasi Kilat Tim Perintis Presisi Polres Metro Depok',
  },
  {
    rank: 4,
    id: 'ZONE-04',
    name: 'Jl. Manggarai Utara (Underpass Rel Kereta)',
    region: 'Jakarta Selatan',
    city: 'DKI Jakarta',
    coordinates: { lat: -6.2104, lng: 106.8502 },
    incidentCount: 15,
    riskScore: 72,
    dangerLevel: 'Rawan',
    dominantCategory: 'Pelecehan',
    peakHours: '22.00 - 03.30 WIB',
    trend: 'down',
    trendPercent: -5.4,
    policeDistanceMeters: 400,
    lightingStatus: 'Minim',
    recommendedIntervention: 'Penerangan Koridor Dishub & Penugasan Linmas Stasiun Terpadu',
  },
  {
    rank: 5,
    id: 'ZONE-05',
    name: 'Jl. KH Noer Ali (Kalimalang Segmen Caman)',
    region: 'Bekasi',
    city: 'Jawa Barat',
    coordinates: { lat: -6.2489, lng: 106.9697 },
    incidentCount: 14,
    riskScore: 68,
    dangerLevel: 'Rawan',
    dominantCategory: 'Begal',
    peakHours: '00.30 - 04.30 WIB',
    trend: 'up',
    trendPercent: 12.0,
    policeDistanceMeters: 1400,
    lightingStatus: 'Minim',
    recommendedIntervention: 'Pembangunan Pos Pantau Terpadu Perbatasan Jakarta-Bekasi',
  },
  {
    rank: 6,
    id: 'ZONE-06',
    name: 'Jl. Daan Mogot Km 14 (Flyover Pesing)',
    region: 'Jakarta Barat',
    city: 'DKI Jakarta',
    coordinates: { lat: -6.1601, lng: 106.7682 },
    incidentCount: 12,
    riskScore: 65,
    dangerLevel: 'Rawan',
    dominantCategory: 'Begal',
    peakHours: '23.00 - 03.30 WIB',
    trend: 'stable',
    trendPercent: 1.2,
    policeDistanceMeters: 650,
    lightingStatus: 'Sedang',
    recommendedIntervention: 'Ronda Patroli Mobile Malam Hari Koridor Daan Mogot',
  },
  {
    rank: 7,
    id: 'ZONE-07',
    name: 'Jl. RE Martadinata (Ancol Selatan)',
    region: 'Jakarta Utara',
    city: 'DKI Jakarta',
    coordinates: { lat: -6.1268, lng: 106.8395 },
    incidentCount: 11,
    riskScore: 62,
    dangerLevel: 'Rawan',
    dominantCategory: 'Begal',
    peakHours: '01.00 - 04.00 WIB',
    trend: 'up',
    trendPercent: 6.5,
    policeDistanceMeters: 1100,
    lightingStatus: 'Minim',
    recommendedIntervention: 'Perbaikan Lampu Penerangan Jalan Tol & CCTV Pelabuhan',
  },
  {
    rank: 8,
    id: 'ZONE-08',
    name: 'Jl. Otista Raya (Koridor Halim Cawang)',
    region: 'Jakarta Timur',
    city: 'DKI Jakarta',
    coordinates: { lat: -6.2435, lng: 106.8681 },
    incidentCount: 10,
    riskScore: 57,
    dangerLevel: 'Waspada',
    dominantCategory: 'Kecelakaan',
    peakHours: '21.00 - 02.00 WIB',
    trend: 'down',
    trendPercent: -10.2,
    policeDistanceMeters: 550,
    lightingStatus: 'Sedang',
    recommendedIntervention: 'Pemasangan Speed Trap & Rambu Bahaya Persimpangan',
  },
  {
    rank: 9,
    id: 'ZONE-09',
    name: 'Jl. Letjen S. Parman (Tomang Underpass)',
    region: 'Jakarta Barat',
    city: 'DKI Jakarta',
    coordinates: { lat: -6.1772, lng: 106.7915 },
    incidentCount: 9,
    riskScore: 54,
    dangerLevel: 'Waspada',
    dominantCategory: 'Infrastruktur',
    peakHours: '23.30 - 03.30 WIB',
    trend: 'down',
    trendPercent: -8.0,
    policeDistanceMeters: 500,
    lightingStatus: 'Sedang',
    recommendedIntervention: 'Perbaikan Aspal Berlubang & Pompa Drainase Jalan',
  },
  {
    rank: 10,
    id: 'ZONE-10',
    name: 'Jl. Perintis Kemerdekaan (Pulogadung Koridor)',
    region: 'Jakarta Timur',
    city: 'DKI Jakarta',
    coordinates: { lat: -6.1895, lng: 106.9015 },
    incidentCount: 8,
    riskScore: 51,
    dangerLevel: 'Waspada',
    dominantCategory: 'Begal',
    peakHours: '00.00 - 04.00 WIB',
    trend: 'down',
    trendPercent: -12.5,
    policeDistanceMeters: 700,
    lightingStatus: 'Sedang',
    recommendedIntervention: 'Peningkatan Frekuensi Sambang Patroli Wilayah Polsek',
  },
];

// Dekomposisi Faktor Penyebab Kerawanan Ruas Jalan (Dimensi Analisis Akar Masalah)
export const mockContributingFactors: ContributingFactorItem[] = [
  {
    factor: 'Kondisi Penerangan Jalan (PJU Padam / Minim)',
    percentage: 38.5,
    impactLevel: 'Kritis',
    description: '82% insiden begal dan curas malam hari terjadi pada ruas jalan dengan intensitas cahaya di bawah 5 lux.',
  },
  {
    factor: 'Jarak Geodesik Pos Polisi / Pos Pantau Terlalu Jauh (>800m)',
    percentage: 27.2,
    impactLevel: 'Tinggi',
    description: 'Respon cepat intervensi aparat membutuhkan lebih dari 12 menit pada ruas tanpa pos siaga terdekat.',
  },
  {
    factor: 'Karakteristik Jalur Sunyi & Minim Hunian Warga',
    percentage: 21.8,
    impactLevel: 'Tinggi',
    description: 'Jalur underpass, flyover non-tol, atau dinding beton tinggi mengurangi pengawasan sosial alami.',
  },
  {
    factor: 'Kerusakan Fisik Jalan (Lubang Aspal & Drainase Rusak)',
    percentage: 12.5,
    impactLevel: 'Sedang',
    description: 'Menyebabkan pengendara memperlambat laju kendaraan secara mendadak sehingga rentan disergap.',
  },
];

// Profil Komunitas Penglaju & Demografi Pelapor (Dimensi Pelapor & Pengguna)
export const mockReporterDemographics: ReporterDemographicItem[] = [
  {
    group: 'Pengemudi Ojek Online & Kurir Logistik Malam',
    percentage: 48.0,
    activeCount: 12480,
    avgTrustScore: 92.4,
    verificationRate: 91.2,
  },
  {
    group: 'Pekerja Shift Malam & Komuter Korporat',
    percentage: 34.0,
    activeCount: 8840,
    avgTrustScore: 88.5,
    verificationRate: 86.8,
  },
  {
    group: 'Warga Pemukiman & Pejalan Kaki Sekitar',
    percentage: 18.0,
    activeCount: 4680,
    avgTrustScore: 78.2,
    verificationRate: 74.5,
  },
];

export const mockTrendDatasets: Record<AnalyticsTimeRange, TrendTimePoint[]> = {
  '7d': [
    { date: '11 Sep', label: 'Jumat, 11 Sep', total: 34, begal: 14, pelecehan: 8, kecelakaan: 7, infrastruktur: 4, lainnya: 1, regionJaksel: 11, regionJakpus: 7, regionJakbar: 5, regionJaktim: 6, regionJakut: 3, regionBodetabek: 2 },
    { date: '12 Sep', label: 'Sabtu, 12 Sep', total: 42, begal: 19, pelecehan: 10, kecelakaan: 8, infrastruktur: 3, lainnya: 2, regionJaksel: 14, regionJakpus: 9, regionJakbar: 6, regionJaktim: 7, regionJakut: 4, regionBodetabek: 2 },
    { date: '13 Sep', label: 'Minggu, 13 Sep', total: 39, begal: 18, pelecehan: 8, kecelakaan: 7, infrastruktur: 4, lainnya: 2, regionJaksel: 13, regionJakpus: 8, regionJakbar: 6, regionJaktim: 7, regionJakut: 3, regionBodetabek: 2 },
    { date: '14 Sep', label: 'Senin, 14 Sep', total: 26, begal: 10, pelecehan: 6, kecelakaan: 5, infrastruktur: 4, lainnya: 1, regionJaksel: 8, regionJakpus: 5, regionJakbar: 4, regionJaktim: 5, regionJakut: 2, regionBodetabek: 2 },
    { date: '15 Sep', label: 'Selasa, 15 Sep', total: 29, begal: 11, pelecehan: 7, kecelakaan: 6, infrastruktur: 4, lainnya: 1, regionJaksel: 9, regionJakpus: 6, regionJakbar: 4, regionJaktim: 6, regionJakut: 2, regionBodetabek: 2 },
    { date: '16 Sep', label: 'Rabu, 16 Sep', total: 31, begal: 13, pelecehan: 7, kecelakaan: 6, infrastruktur: 3, lainnya: 2, regionJaksel: 10, regionJakpus: 6, regionJakbar: 5, regionJaktim: 6, regionJakut: 2, regionBodetabek: 2 },
    { date: '17 Sep', label: 'Kamis, 17 Sep', total: 35, begal: 16, pelecehan: 8, kecelakaan: 6, infrastruktur: 3, lainnya: 2, regionJaksel: 12, regionJakpus: 7, regionJakbar: 5, regionJaktim: 6, regionJakut: 3, regionBodetabek: 2 },
  ],
  '30d': [
    { date: 'Mgg 1', label: 'Pekan 1 (24-30 Agt)', total: 184, begal: 78, pelecehan: 42, kecelakaan: 38, infrastruktur: 18, lainnya: 8, regionJaksel: 56, regionJakpus: 38, regionJakbar: 28, regionJaktim: 36, regionJakut: 16, regionBodetabek: 10 },
    { date: 'Mgg 2', label: 'Pekan 2 (31 Agt-6 Sep)', total: 198, begal: 85, pelecehan: 46, kecelakaan: 39, infrastruktur: 20, lainnya: 8, regionJaksel: 62, regionJakpus: 40, regionJakbar: 31, regionJaktim: 38, regionJakut: 17, regionBodetabek: 10 },
    { date: 'Mgg 3', label: 'Pekan 3 (7-13 Sep)', total: 215, begal: 94, pelecehan: 49, kecelakaan: 43, infrastruktur: 21, lainnya: 8, regionJaksel: 68, regionJakpus: 43, regionJakbar: 34, regionJaktim: 41, regionJakut: 18, regionBodetabek: 11 },
    { date: 'Mgg 4', label: 'Pekan 4 (14-17 Sep berjalan)', total: 121, begal: 50, pelecehan: 28, kecelakaan: 23, infrastruktur: 14, lainnya: 6, regionJaksel: 39, regionJakpus: 24, regionJakbar: 18, regionJaktim: 23, regionJakut: 10, regionBodetabek: 7 },
  ],
  '90d': [
    { date: 'Jul Awal', label: '1 - 15 Jul 2026', total: 340, begal: 145, pelecehan: 80, kecelakaan: 65, infrastruktur: 35, lainnya: 15, regionJaksel: 105, regionJakpus: 70, regionJakbar: 55, regionJaktim: 62, regionJakut: 30, regionBodetabek: 18 },
    { date: 'Jul Akhir', label: '16 - 31 Jul 2026', total: 365, begal: 155, pelecehan: 85, kecelakaan: 70, infrastruktur: 38, lainnya: 17, regionJaksel: 112, regionJakpus: 75, regionJakbar: 58, regionJaktim: 66, regionJakut: 33, regionBodetabek: 21 },
    { date: 'Agt Awal', label: '1 - 15 Agt 2026', total: 380, begal: 162, pelecehan: 88, kecelakaan: 72, infrastruktur: 40, lainnya: 18, regionJaksel: 118, regionJakpus: 78, regionJakbar: 60, regionJaktim: 69, regionJakut: 34, regionBodetabek: 21 },
    { date: 'Agt Akhir', label: '16 - 31 Agt 2026', total: 395, begal: 170, pelecehan: 91, kecelakaan: 75, infrastruktur: 41, lainnya: 18, regionJaksel: 122, regionJakpus: 81, regionJakbar: 63, regionJaktim: 72, regionJakut: 36, regionBodetabek: 21 },
    { date: 'Sep Awal', label: '1 - 15 Sep 2026', total: 412, begal: 178, pelecehan: 95, kecelakaan: 78, infrastruktur: 42, lainnya: 19, regionJaksel: 128, regionJakpus: 84, regionJakbar: 66, regionJaktim: 75, regionJakut: 37, regionBodetabek: 22 },
  ],
  '1y': [
    { date: 'Okt 25', label: 'Oktober 2025', total: 640, begal: 270, pelecehan: 150, kecelakaan: 120, infrastruktur: 70, lainnya: 30, regionJaksel: 198, regionJakpus: 130, regionJakbar: 102, regionJaktim: 116, regionJakut: 58, regionBodetabek: 36 },
    { date: 'Nov 25', label: 'November 2025', total: 680, begal: 290, pelecehan: 158, kecelakaan: 126, infrastruktur: 74, lainnya: 32, regionJaksel: 210, regionJakpus: 139, regionJakbar: 108, regionJaktim: 124, regionJakut: 61, regionBodetabek: 38 },
    { date: 'Des 25', label: 'Desember 2025', total: 720, begal: 310, pelecehan: 168, kecelakaan: 132, infrastruktur: 76, lainnya: 34, regionJaksel: 224, regionJakpus: 147, regionJakbar: 114, regionJaktim: 131, regionJakut: 65, regionBodetabek: 39 },
    { date: 'Jan 26', label: 'Januari 2026', total: 650, begal: 275, pelecehan: 152, kecelakaan: 122, infrastruktur: 71, lainnya: 30, regionJaksel: 201, regionJakpus: 132, regionJakbar: 103, regionJaktim: 118, regionJakut: 59, regionBodetabek: 37 },
    { date: 'Feb 26', label: 'Februari 2026', total: 620, begal: 260, pelecehan: 145, kecelakaan: 118, infrastruktur: 68, lainnya: 29, regionJaksel: 192, regionJakpus: 126, regionJakbar: 98, regionJaktim: 113, regionJakut: 56, regionBodetabek: 35 },
    { date: 'Mar 26', label: 'Maret 2026', total: 690, begal: 295, pelecehan: 160, kecelakaan: 128, infrastruktur: 75, lainnya: 32, regionJaksel: 214, regionJakpus: 141, regionJakbar: 109, regionJaktim: 126, regionJakut: 62, regionBodetabek: 38 },
    { date: 'Apr 26', label: 'April 2026', total: 710, begal: 305, pelecehan: 165, kecelakaan: 130, infrastruktur: 77, lainnya: 33, regionJaksel: 220, regionJakpus: 145, regionJakbar: 112, regionJaktim: 129, regionJakut: 64, regionBodetabek: 40 },
    { date: 'Mei 26', label: 'Mei 2026', total: 740, begal: 318, pelecehan: 172, kecelakaan: 136, infrastruktur: 80, lainnya: 34, regionJaksel: 230, regionJakpus: 151, regionJakbar: 117, regionJaktim: 135, regionJakut: 67, regionBodetabek: 40 },
    { date: 'Jun 26', label: 'Juni 2026', total: 760, begal: 328, pelecehan: 176, kecelakaan: 140, infrastruktur: 81, lainnya: 35, regionJaksel: 236, regionJakpus: 155, regionJakbar: 120, regionJaktim: 138, regionJakut: 68, regionBodetabek: 43 },
    { date: 'Jul 26', label: 'Juli 2026', total: 790, begal: 342, pelecehan: 183, kecelakaan: 144, infrastruktur: 85, lainnya: 36, regionJaksel: 245, regionJakpus: 161, regionJakbar: 125, regionJaktim: 144, regionJakut: 71, regionBodetabek: 44 },
    { date: 'Agt 26', label: 'Agustus 2026', total: 815, begal: 354, pelecehan: 189, kecelakaan: 148, infrastruktur: 87, lainnya: 37, regionJaksel: 253, regionJakpus: 166, regionJakbar: 129, regionJaktim: 148, regionJakut: 73, regionBodetabek: 46 },
    { date: 'Sep 26', label: 'September 2026', total: 718, begal: 312, pelecehan: 167, kecelakaan: 130, infrastruktur: 77, lainnya: 32, regionJaksel: 223, regionJakpus: 146, regionJakbar: 113, regionJaktim: 131, regionJakut: 65, regionBodetabek: 40 },
  ],
};

// ==========================================
// 6. MANAJEMEN KONTEN MASTER & KONFIGURASI SISTEM
// ==========================================

export const mockMasterCategories: IncidentCategoryMaster[] = [
  {
    id: 'CAT-01',
    name: 'Begal & Kejahatan Jalanan Kekerasan',
    slug: 'begal',
    iconName: 'AlertTriangle',
    defaultSeverity: 9,
    severityLabel: 'Kritis',
    colorHex: '#f43f5e',
    description: 'Tindak kejahatan dengan ancaman senjata tajam, pemerasan paksa, atau perampasan kendaraan bermotor.',
    reportCount: 312,
    isActive: true,
    createdAt: '2026-01-10T08:00:00Z',
    updatedAt: '2026-09-10T14:30:00Z',
  },
  {
    id: 'CAT-02',
    name: 'Curas & Penjambretan Bergerak',
    slug: 'curas',
    iconName: 'ShieldAlert',
    defaultSeverity: 8,
    severityLabel: 'Kritis',
    colorHex: '#e11d48',
    description: 'Pencurian dengan kekerasan bergerak menggunakan sepeda motor menyasar tas, gawai, dan barang berharga.',
    reportCount: 184,
    isActive: true,
    createdAt: '2026-01-12T09:00:00Z',
    updatedAt: '2026-09-08T11:20:00Z',
  },
  {
    id: 'CAT-03',
    name: 'Pelecehan Seksual & Tindakan Asusila',
    slug: 'pelecehan',
    iconName: 'Footprints',
    defaultSeverity: 8,
    severityLabel: 'Kritis',
    colorHex: '#d946ef',
    description: 'Catcalling agresif, begal payudara, penguntitan malam hari, atau pelecehan fisik di area transit jalanan.',
    reportCount: 167,
    isActive: true,
    createdAt: '2026-01-15T10:00:00Z',
    updatedAt: '2026-09-12T16:40:00Z',
  },
  {
    id: 'CAT-04',
    name: 'Minim Penerangan / Lampu PJU Mati',
    slug: 'minim-penerangan',
    iconName: 'SunDim',
    defaultSeverity: 5,
    severityLabel: 'Sedang',
    colorHex: '#06b6d4',
    description: 'Lampu Penerangan Jalan Umum padam sepanjang ruas koridor yang menurunkan jarak pandang dan visibilitas.',
    reportCount: 128,
    isActive: true,
    createdAt: '2026-01-18T11:00:00Z',
    updatedAt: '2026-09-15T09:10:00Z',
  },
  {
    id: 'CAT-05',
    name: 'Jalan Berlubang & Aspal Rusak Parah',
    slug: 'jalan-rusak',
    iconName: 'Car',
    defaultSeverity: 4,
    severityLabel: 'Sedang',
    colorHex: '#38bdf8',
    description: 'Kerusakan kontur jalan, lubang menganga tanpa tanda peringatan, atau sisa galian yang membahayakan roda dua.',
    reportCount: 95,
    isActive: true,
    createdAt: '2026-01-20T13:00:00Z',
    updatedAt: '2026-09-14T10:15:00Z',
  },
  {
    id: 'CAT-06',
    name: 'Kecelakaan Lalu Lintas & Tabrakan',
    slug: 'kecelakaan',
    iconName: 'AlertTriangle',
    defaultSeverity: 7,
    severityLabel: 'Tinggi',
    colorHex: '#f59e0b',
    description: 'Insiden tabrakan kendaraan, pengendara terjatuh, atau kecelakaan beruntun yang menutup lajur jalan.',
    reportCount: 130,
    isActive: true,
    createdAt: '2026-01-22T14:30:00Z',
    updatedAt: '2026-09-16T17:00:00Z',
  },
  {
    id: 'CAT-07',
    name: 'Titik Rawan Tawuran & Kerumunan Liar',
    slug: 'tawuran',
    iconName: 'ShieldAlert',
    defaultSeverity: 8,
    severityLabel: 'Kritis',
    colorHex: '#ea580c',
    description: 'Indikasi bentrokan kelompok pemuda, balap liar dini hari, atau blokade jalan tanpa izin.',
    reportCount: 82,
    isActive: true,
    createdAt: '2026-02-01T08:30:00Z',
    updatedAt: '2026-09-11T13:20:00Z',
  },
  {
    id: 'CAT-08',
    name: 'Genangan Air & Banjir Ruas Jalan',
    slug: 'genangan-air',
    iconName: 'Waves',
    defaultSeverity: 4,
    severityLabel: 'Sedang',
    colorHex: '#0284c7',
    description: 'Genangan air melebihi 20 cm yang berpotensi mematikan mesin kendaraan dan menyembunyikan lubang jalan.',
    reportCount: 46,
    isActive: true,
    createdAt: '2026-02-10T11:20:00Z',
    updatedAt: '2026-09-05T08:40:00Z',
  },
  {
    id: 'CAT-09',
    name: 'Jalur Sunyi & Minim Hunian Warga',
    slug: 'jalur-sunyi',
    iconName: 'Footprints',
    defaultSeverity: 6,
    severityLabel: 'Tinggi',
    colorHex: '#8b5cf6',
    description: 'Koridor terisolasi berpagar beton tinggi atau perkebunan sunyi tanpa pemukiman atau ruko aktif.',
    reportCount: 64,
    isActive: true,
    createdAt: '2026-02-15T15:00:00Z',
    updatedAt: '2026-09-02T16:10:00Z',
  },
  {
    id: 'CAT-10',
    name: 'Lainnya (Non-Kategori Spesifik)',
    slug: 'lainnya',
    iconName: 'HelpCircle',
    defaultSeverity: 3,
    severityLabel: 'Rendah',
    colorHex: '#64748b',
    description: 'Laporan anomali jalan lainnya yang belum terpetakan dalam klasifikasi standar sistem.',
    reportCount: 32,
    isActive: true,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-08-30T10:00:00Z',
  },
];

export const mockRiskThresholds: RiskThresholdConfig = {
  safeMax: 35,
  warningMax: 65,
  criticalMin: 66,
  autoRerouteThreshold: 60,
  lastUpdated: '2026-09-17T18:30:00Z',
  updatedBy: 'Budi Santoso (Superadmin)',
};

export const mockDbscanConfig: DbscanSystemConfig = {
  eps: 450,
  minSamples: 4,
  distanceMetric: 'haversine',
  timeDecayDays: 90,
  clusterWeightMode: 'severity_weighted',
  lastCalibration: '2026-09-17T12:00:00Z',
  simulatedClustersCount: 14,
  simulatedNoisePointsCount: 42,
};

// ==========================================
// 9. MODERASI KONTEN LAPORAN
// ==========================================

export const mockModerationQueue: ModeratedContentItem[] = [
  {
    id: 'MOD-2026-001',
    incidentId: 'INC-2023-006',
    category: 'Begal',
    locationName: 'Flyover Casablanca, Jakarta Selatan',
    timestamp: '2026-09-17T20:45:00Z',
    reporterName: 'Fajar Pratama (Ojol)',
    reporterTrustScore: 92,
    incidentVerificationStatus: 'Verified',
    moderationStatus: 'Pending',
    originalText: 'Terjadi pembegalan terhadap pemotor Honda Beat B 4821 TKQ. Korban bernama Rian Sutedja HP 0812-9988-7766 terluka di lengan kanan dan ditolong rekan driver ojol.',
    redactedText: 'Terjadi pembegalan terhadap pemotor Honda Beat [PLAT DIREDAKSI]. Korban bernama [NAMA DISAMARKAN] HP 0812-****-**** terluka di lengan kanan dan ditolong rekan driver ojol.',
    hasImage: true,
    imageTheme: 'street_dark',
    isImageBlurred: false,
    blurTarget: 'None',
    autoFlags: [
      { type: 'face_pii', label: 'Wajah Korban Terdeteksi', confidence: 97, severity: 'High', snippet: 'Wajah korban tampak jelas di sudut kiri frame' },
      { type: 'plate_pii', label: 'Plat Nomor Kendaraan', confidence: 94, severity: 'High', snippet: 'Plat B 4821 TKQ teridentifikasi OCR' },
      { type: 'phone_pii', label: 'Nomor Ponsel Pribadi', confidence: 99, severity: 'High', snippet: '0812-9988-7766' },
      { type: 'graphic_violence', label: 'Indikasi Luka / Sensitif', confidence: 86, severity: 'Medium', snippet: 'Deteksi bercak luka pada lengan' },
    ],
    moderationNote: 'Perlu sensor wajah korban dan samarkan plat nomor sebelum publish ke peta publik.',
  },
  {
    id: 'MOD-2026-002',
    incidentId: 'INC-2023-003',
    category: 'Pelecehan',
    locationName: 'Underpass Stasiun Manggarai, Jaksel',
    timestamp: '2026-09-17T19:15:00Z',
    reporterName: 'Siti Nurhaliza',
    reporterTrustScore: 88,
    incidentVerificationStatus: 'Verified',
    moderationStatus: 'Redacted',
    originalText: 'Ada pria bertopi hitam melakukan pelecehan verbal catcalling dan meraba tas pejalan kaki wanita yang melintas lorong stasiun.',
    redactedText: 'Ada pria bertopi hitam melakukan tindakan pelecehan verbal dan meraba tas pejalan kaki wanita yang melintas lorong stasiun.',
    hasImage: true,
    imageTheme: 'cctv_alley',
    isImageBlurred: true,
    blurTarget: 'Face',
    autoFlags: [
      { type: 'face_pii', label: 'Wajah Pejalan Kaki Publik', confidence: 89, severity: 'Medium', snippet: '3 orang warga sekitar terlihat di latar belakang' },
    ],
    moderatedBy: 'Budi Santoso (Admin)',
    moderatedAt: '2026-09-17T19:30:00Z',
    moderationNote: 'Sensor wajah pejalan kaki diterapkan. Konten aman ditampilkan di peta publik.',
  },
  {
    id: 'MOD-2026-003',
    incidentId: 'INC-2023-002',
    category: 'Kecelakaan',
    locationName: 'Flyover Pasar Rebo, Jakarta Timur',
    timestamp: '2026-09-17T18:10:00Z',
    reporterName: 'Hendra Gunawan',
    reporterTrustScore: 85,
    incidentVerificationStatus: 'Verified',
    moderationStatus: 'Pending',
    originalText: 'Tabrakan beruntun motor vs truk. Sopir anjing bangsat ngebut gila-gilaan gak mikir nyawa orang, darah berceceran di aspal.',
    redactedText: 'Tabrakan beruntun motor vs truk. Sopir [KATA KASAR DIREDAKSI] melaju kencang membahayakan, korban dievakuasi warga ke RS terdekat.',
    hasImage: true,
    imageTheme: 'accident_debris',
    isImageBlurred: false,
    blurTarget: 'None',
    autoFlags: [
      { type: 'offensive_text', label: 'Ujaran Kasar / Profanity', confidence: 99, severity: 'High', snippet: 'anjing bangsat ngebut' },
      { type: 'graphic_violence', label: 'Konten Darah / Grafis', confidence: 91, severity: 'High', snippet: 'Darah dan serpihan benturan terekam' },
      { type: 'plate_pii', label: 'Plat Nomor Truk', confidence: 88, severity: 'Medium', snippet: 'Plat kendaraan terdeteksi' },
    ],
    moderationNote: 'Wajib redact teks kata kasar dan blur foto benturan sebelum rilis publik.',
  },
  {
    id: 'MOD-2026-004',
    incidentId: 'INC-2023-004',
    category: 'Infrastruktur',
    locationName: 'Kuningan Barat, Jakarta Selatan',
    timestamp: '2026-09-17T16:20:00Z',
    reporterName: 'Bayu Wicaksono',
    reporterTrustScore: 94,
    incidentVerificationStatus: 'Verified',
    moderationStatus: 'Approved',
    originalText: 'Lampu PJU padam sepanjang 400 meter di dekat putaran balik Kuningan. Jalanan gelap gulita hanya mengandalkan lampu kendaraan.',
    redactedText: 'Lampu PJU padam sepanjang 400 meter di dekat putaran balik Kuningan. Jalanan gelap gulita hanya mengandalkan lampu kendaraan.',
    hasImage: true,
    imageTheme: 'pothole_puddle',
    isImageBlurred: false,
    blurTarget: 'None',
    autoFlags: [],
    moderatedBy: 'Siti Aminah (Moderator)',
    moderatedAt: '2026-09-17T16:35:00Z',
    moderationNote: 'Laporan bersih tanpa PII. Foto infrastruktur aman untuk publik.',
  },
  {
    id: 'MOD-2026-005',
    incidentId: 'INC-2023-005',
    category: 'Lainnya',
    locationName: 'Menteng Jaya, Jakarta Pusat',
    timestamp: '2026-09-17T14:00:00Z',
    reporterName: 'Akun Tamu (USR-105)',
    reporterTrustScore: 30,
    incidentVerificationStatus: 'Rejected',
    moderationStatus: 'Rejected',
    originalText: 'Woy ada hantu pocong terbang di atas pohon jalan Menteng ati-ati kalian semua haha promosi follow ig @hantujkt.',
    redactedText: '[KONTEN DITOLAK KARENA SPAM]',
    hasImage: true,
    imageTheme: 'cctv_alley',
    isImageBlurred: true,
    blurTarget: 'Full',
    autoFlags: [
      { type: 'offensive_text', label: 'Spam / Promosi Medsos', confidence: 95, severity: 'High', snippet: 'promosi follow ig @hantujkt' },
      { type: 'blurry_media', label: 'Foto Buram / Tidak Relevan', confidence: 96, severity: 'Medium', snippet: 'Gambar gelap buram tidak valid' },
    ],
    moderatedBy: 'Budi Santoso (Admin)',
    moderatedAt: '2026-09-17T14:15:00Z',
    moderationNote: 'Konten spam palsu. Disembunyikan dari seluruh aplikasi.',
  },
  {
    id: 'MOD-2026-006',
    incidentId: 'INC-2023-007',
    category: 'Begal',
    locationName: 'Jl. KH Noer Ali (Kalimalang Caman)',
    timestamp: '2026-09-17T11:40:00Z',
    reporterName: 'Rian Maulana (Kurir)',
    reporterTrustScore: 89,
    incidentVerificationStatus: 'Verified',
    moderationStatus: 'Pending',
    originalText: 'Pelaku 2 orang mengendarai NMAX hitam tanpa plat mencoba memepet paket logistik saya. Saya berhasil kabur ke warung kopi Pak Joko telepon 0857-1122-3344.',
    redactedText: 'Pelaku 2 orang mengendarai NMAX hitam tanpa plat mencoba memepet kurir logistik. Korban berhasil mengamankan diri ke warung warga terdekat.',
    hasImage: false,
    imageTheme: 'street_dark',
    isImageBlurred: false,
    blurTarget: 'None',
    autoFlags: [
      { type: 'phone_pii', label: 'Nomor Telepon Pribadi', confidence: 98, severity: 'High', snippet: '0857-1122-3344' },
    ],
    moderationNote: 'Laporan valid kepolisian, nomor telepon warga perlu disamarkan dari feed umum.',
  },
];

// 10. MANAJEMEN INTEGRASI EKSTERNAL MOCK DATA
export const mockPoliceIntegrations: PoliceIntegrationConfig[] = [
  {
    id: 'INT-POLDA-01',
    name: 'Polda Metro Jaya - Bareskrim Pusiknas Feed',
    agency: 'Kepolisian Daerah Metropolitan Jakarta Raya',
    endpointUrl: 'https://api-pusiknas.polri.go.id/v2/feeds/jabodetabek/crimes',
    authType: 'api_key',
    authCredentialMasked: 'pol_live_9f82••••••••••••••4a91',
    dataFormat: 'JSON',
    syncSchedule: 'every_15_mins',
    syncScheduleLabel: 'Setiap 15 Menit',
    cronExpression: '*/15 * * * *',
    status: 'Connected',
    lastSyncAt: '2026-09-17T21:15:00Z',
    lastSyncStatus: 'Success',
    autoImportVerified: true,
    timeoutMs: 8000,
    retryCount: 3,
    totalImportedAllTime: 1420,
  },
  {
    id: 'INT-KORLANTAS-02',
    name: 'Korlantas Polri IRSMS Laka Lantas & Kemacetan',
    agency: 'Korps Lalu Lintas Kepolisian Republik Indonesia',
    endpointUrl: 'https://irsms.korlantas.polri.go.id/api/v1/incidents/spatial',
    authType: 'bearer_token',
    authCredentialMasked: 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9••••••',
    dataFormat: 'GeoJSON',
    syncSchedule: 'hourly',
    syncScheduleLabel: 'Setiap 1 Jam',
    cronExpression: '0 * * * *',
    status: 'Connected',
    lastSyncAt: '2026-09-17T21:00:00Z',
    lastSyncStatus: 'Success',
    autoImportVerified: true,
    timeoutMs: 12000,
    retryCount: 2,
    totalImportedAllTime: 892,
  },
  {
    id: 'INT-DISHUB-03',
    name: 'Command Center Dishub DKI Jakarta Realtime Feed',
    agency: 'Dinas Perhubungan Provinsi DKI Jakarta',
    endpointUrl: 'https://smartcity.jakarta.go.id/gateway/dishub/v3/traffic-anomalies',
    authType: 'api_key',
    authCredentialMasked: 'dki_sc_live_bb91••••••••••••77a3',
    dataFormat: 'JSON',
    syncSchedule: 'every_30_mins',
    syncScheduleLabel: 'Setiap 30 Menit',
    cronExpression: '*/30 * * * *',
    status: 'Connected',
    lastSyncAt: '2026-09-17T21:00:00Z',
    lastSyncStatus: 'Success',
    autoImportVerified: false,
    timeoutMs: 5000,
    retryCount: 3,
    totalImportedAllTime: 430,
  },
  {
    id: 'INT-POLRES-BOGOR',
    name: 'Polres Metro Depok & Bogor Perbatasan Feed',
    agency: 'Polres Metro Depok - Bag Ops',
    endpointUrl: 'https://rest-spkt.polresdepok.id/services/soap/incident-export.xml',
    authType: 'basic_auth',
    authCredentialMasked: 'spkt_ops_user:••••••••••••',
    dataFormat: 'XML_SOAP',
    syncSchedule: 'daily_midnight',
    syncScheduleLabel: 'Harian (00:00 WIB)',
    cronExpression: '0 0 * * *',
    status: 'Error',
    lastSyncAt: '2026-09-17T00:00:00Z',
    lastSyncStatus: 'Failed',
    autoImportVerified: false,
    timeoutMs: 15000,
    retryCount: 1,
    totalImportedAllTime: 115,
  },
];

export const mockSyncLogs: SyncLogEntry[] = [
  {
    id: 'SYNC-2026-901',
    sourceId: 'INT-POLDA-01',
    sourceName: 'Polda Metro Jaya - Bareskrim Pusiknas Feed',
    startedAt: '2026-09-17T21:15:00Z',
    completedAt: '2026-09-17T21:15:02Z',
    durationMs: 1840,
    recordsFetched: 18,
    recordsImported: 15,
    recordsDuplicate: 3,
    recordsFailed: 0,
    status: 'Success',
    triggeredBy: 'Automated Cron',
  },
  {
    id: 'SYNC-2026-902',
    sourceId: 'INT-KORLANTAS-02',
    sourceName: 'Korlantas Polri IRSMS Laka Lantas & Kemacetan',
    startedAt: '2026-09-17T21:00:00Z',
    completedAt: '2026-09-17T21:00:03Z',
    durationMs: 3120,
    recordsFetched: 32,
    recordsImported: 29,
    recordsDuplicate: 2,
    recordsFailed: 1,
    status: 'Partial',
    errorDetails: [
      "Record #14: Koordinat WGS84 tidak valid (lat: -999.00, lng: 0.00) - dilewati.",
    ],
    triggeredBy: 'Automated Cron',
  },
  {
    id: 'SYNC-2026-903',
    sourceId: 'INT-DISHUB-03',
    sourceName: 'Command Center Dishub DKI Jakarta Realtime Feed',
    startedAt: '2026-09-17T21:00:00Z',
    completedAt: '2026-09-17T21:00:01Z',
    durationMs: 950,
    recordsFetched: 12,
    recordsImported: 12,
    recordsDuplicate: 0,
    recordsFailed: 0,
    status: 'Success',
    triggeredBy: 'Automated Cron',
  },
  {
    id: 'SYNC-2026-904',
    sourceId: 'INT-POLDA-01',
    sourceName: 'Polda Metro Jaya - Bareskrim Pusiknas Feed',
    startedAt: '2026-09-17T20:30:00Z',
    completedAt: '2026-09-17T20:30:02Z',
    durationMs: 1720,
    recordsFetched: 24,
    recordsImported: 22,
    recordsDuplicate: 2,
    recordsFailed: 0,
    status: 'Success',
    triggeredBy: 'Automated Cron',
  },
  {
    id: 'SYNC-2026-905',
    sourceId: 'INT-POLRES-BOGOR',
    sourceName: 'Polres Metro Depok & Bogor Perbatasan Feed',
    startedAt: '2026-09-17T00:00:00Z',
    completedAt: '2026-09-17T00:00:15Z',
    durationMs: 15000,
    recordsFetched: 0,
    recordsImported: 0,
    recordsDuplicate: 0,
    recordsFailed: 0,
    status: 'Failed',
    errorDetails: [
      "ERR_CONNECTION_TIMEDOUT: Server SOAP endpoint https://rest-spkt.polresdepok.id tidak merespons setelah 15000ms.",
      "SSL Certificate Handshake Warning: Sertifikat kedaluwarsa sejak 10 September 2026."
    ],
    triggeredBy: 'Automated Cron',
  },
  {
    id: 'SYNC-2026-906',
    sourceId: 'INT-POLDA-01',
    sourceName: 'Polda Metro Jaya - Bareskrim Pusiknas Feed',
    startedAt: '2026-09-16T18:45:10Z',
    completedAt: '2026-09-16T18:45:12Z',
    durationMs: 2100,
    recordsFetched: 45,
    recordsImported: 43,
    recordsDuplicate: 2,
    recordsFailed: 0,
    status: 'Success',
    triggeredBy: 'Manual Superadmin',
  },
];

export const mockPartnerApiKeys: ExternalPartnerApiKey[] = [
  {
    id: 'KEY-PARTNER-01',
    partnerName: 'Gojek Rider Safety Telematics',
    partnerType: 'Ride Hailing',
    apiKeyMasked: 'ja_live_gojek_8f19••••••••••••••••33e1',
    apiKeyRawFull: 'ja_live_gojek_8f190bc1294fe78912aa4401bb2233e1',
    status: 'Active',
    rateLimit: {
      requestsPerMinute: 120,
      requestsPerHour: 5000,
      requestsPerDay: 50000,
    },
    usageToday: {
      totalRequests: 28450,
      quotaPercentage: 56.9,
      lastActiveAt: '2026-09-17T21:24:10Z',
    },
    scopes: ['routes:read_risk', 'clusters:read', 'telemetry:write'],
    contactEmail: 'engineering-safety@gojek.com',
    createdAt: '2026-01-15T08:00:00Z',
    expiresAt: '2027-01-15T08:00:00Z',
  },
  {
    id: 'KEY-PARTNER-02',
    partnerName: 'Grab Shield Incident Routing',
    partnerType: 'Ride Hailing',
    apiKeyMasked: 'ja_live_grab_e330••••••••••••••••990a',
    apiKeyRawFull: 'ja_live_grab_e330f81b338271cc44a7812bc881990a',
    status: 'Active',
    rateLimit: {
      requestsPerMinute: 120,
      requestsPerHour: 5000,
      requestsPerDay: 50000,
    },
    usageToday: {
      totalRequests: 34120,
      quotaPercentage: 68.2,
      lastActiveAt: '2026-09-17T21:22:45Z',
    },
    scopes: ['routes:read_risk', 'clusters:read'],
    contactEmail: 'security-partnerships@grabtaxi.com',
    createdAt: '2026-02-01T10:00:00Z',
    expiresAt: '2027-02-01T10:00:00Z',
  },
  {
    id: 'KEY-PARTNER-03',
    partnerName: 'ShopeeFood Fleet Logistics ID',
    partnerType: 'Logistics',
    apiKeyMasked: 'ja_live_spf_b712••••••••••••••••55fc',
    apiKeyRawFull: 'ja_live_spf_b712aa894411ee880011bbffaa2255fc',
    status: 'Active',
    rateLimit: {
      requestsPerMinute: 60,
      requestsPerHour: 2500,
      requestsPerDay: 25000,
    },
    usageToday: {
      totalRequests: 9800,
      quotaPercentage: 39.2,
      lastActiveAt: '2026-09-17T21:18:00Z',
    },
    scopes: ['routes:read_risk'],
    contactEmail: 'fleet-dev@shopee.co.id',
    createdAt: '2026-03-10T14:30:00Z',
    expiresAt: '2027-03-10T14:30:00Z',
  },
  {
    id: 'KEY-PARTNER-04',
    partnerName: 'Maxim Driver Alert Network',
    partnerType: 'Ride Hailing',
    apiKeyMasked: 'ja_live_maxim_c991••••••••••••••••11ab',
    apiKeyRawFull: 'ja_live_maxim_c9919933cc4422bb1100ffeeaabb11ab',
    status: 'Suspended',
    rateLimit: {
      requestsPerMinute: 30,
      requestsPerHour: 1000,
      requestsPerDay: 10000,
    },
    usageToday: {
      totalRequests: 1240,
      quotaPercentage: 12.4,
      lastActiveAt: '2026-09-16T19:30:00Z',
    },
    scopes: ['routes:read_risk', 'incidents:report'],
    contactEmail: 'integration@taximaxim.id',
    createdAt: '2026-04-05T09:15:00Z',
    expiresAt: '2027-04-05T09:15:00Z',
  },
  {
    id: 'KEY-PARTNER-05',
    partnerName: 'Dishub DKI Jakarta Smart Mobility Center',
    partnerType: 'Government',
    apiKeyMasked: 'ja_live_dishub_aa40••••••••••••••••66df',
    apiKeyRawFull: 'ja_live_dishub_aa40ff55ee44dd33cc22bb11aa0066df',
    status: 'Active',
    rateLimit: {
      requestsPerMinute: 300,
      requestsPerHour: 15000,
      requestsPerDay: 150000,
    },
    usageToday: {
      totalRequests: 84200,
      quotaPercentage: 56.1,
      lastActiveAt: '2026-09-17T21:25:01Z',
    },
    scopes: ['routes:read_risk', 'clusters:read', 'incidents:report'],
    contactEmail: 'pusdatin@dishub.jakarta.go.id',
    createdAt: '2026-01-01T00:00:00Z',
    expiresAt: '2028-01-01T00:00:00Z',
  },
];

export const mockFieldMappings: FieldMappingRule[] = [
  {
    id: 'MAP-01',
    sourceFieldName: 'kd_kejahatan_polri',
    sourceFieldType: 'string',
    targetInternalField: 'category_id',
    targetFieldLabel: 'Kategori Insiden (ID / Enum)',
    isRequired: true,
    transformationRule: 'map_crime_code_to_category',
    fallbackValue: 'Lainnya',
    sampleSourceValue: '"365"',
    sampleTransformedValue: '"Begal"',
  },
  {
    id: 'MAP-02',
    sourceFieldName: 'waktu_lapor_wib',
    sourceFieldType: 'datetime',
    targetInternalField: 'occurred_at',
    targetFieldLabel: 'Waktu Kejadian (ISO 8601)',
    isRequired: true,
    transformationRule: 'iso_timestamp_parse',
    sampleSourceValue: '"2026-09-17 21:05:00"',
    sampleTransformedValue: '"2026-09-17T14:05:00.000Z"',
  },
  {
    id: 'MAP-03',
    sourceFieldName: 'titik_gps_lat',
    sourceFieldType: 'number',
    targetInternalField: 'latitude',
    targetFieldLabel: 'Garis Lintang (Latitude)',
    isRequired: true,
    transformationRule: 'wgs84_float',
    sampleSourceValue: '"-6.225014"',
    sampleTransformedValue: '-6.225014',
  },
  {
    id: 'MAP-04',
    sourceFieldName: 'titik_gps_lon',
    sourceFieldType: 'number',
    targetInternalField: 'longitude',
    targetFieldLabel: 'Garis Bujur (Longitude)',
    isRequired: true,
    transformationRule: 'wgs84_float',
    sampleSourceValue: '"106.842119"',
    sampleTransformedValue: '106.842119',
  },
  {
    id: 'MAP-05',
    sourceFieldName: 'kronologis_singkat',
    sourceFieldType: 'string',
    targetInternalField: 'description',
    targetFieldLabel: 'Deskripsi / Kronologis Laporan',
    isRequired: true,
    transformationRule: 'normalize_text',
    sampleSourceValue: '"Terjadi penjambretan hp didepan minimarket..."',
    sampleTransformedValue: '"Terjadi penjambretan HP di depan minimarket..."',
  },
  {
    id: 'MAP-06',
    sourceFieldName: 'nomor_laporan_polisi',
    sourceFieldType: 'string',
    targetInternalField: 'source_reference',
    targetFieldLabel: 'Referensi Eksternal (No. LP / ID)',
    isRequired: false,
    transformationRule: 'none',
    sampleSourceValue: '"LP/B/8812/IX/2026/SPKT/POLDA METRO"',
    sampleTransformedValue: '"POLRI-LP/B/8812/IX/2026/SPKT/POLDA METRO"',
  },
  {
    id: 'MAP-07',
    sourceFieldName: 'derajat_kerawanan_ops',
    sourceFieldType: 'number',
    targetInternalField: 'severity_level',
    targetFieldLabel: 'Tingkat Bahaya Default (1-10)',
    isRequired: false,
    transformationRule: 'default_value',
    fallbackValue: '8',
    sampleSourceValue: '"4" (Skala 1-5 Polri)',
    sampleTransformedValue: '8 (Normalisasi ke Skala 10)',
  },
];

// 11. KONFIGURASI NOTIFIKASI REAL-TIME MOCK DATA
export const mockGlobalNotificationSettings: GlobalNotificationSettings = {
  defaultRadiusMeters: 500,
  minRadiusMeters: 200,
  maxRadiusMeters: 2000,
  defaultStartTime: '00:00',
  defaultEndTime: '04:59',
  globalCooldownMinutes: 30,
  emergencyBroadcastEnabled: true,
  pushChannelProvider: 'Firebase Cloud Messaging (FCM High Priority) & Apple APNs',
  lastUpdated: '2026-09-17T18:00:00Z',
  updatedBy: 'Budi Santoso (Superadmin)',
};

export const mockNotificationTemplates: NotificationTemplate[] = [
  {
    id: 'TMPL-WASPADA',
    level: 'Waspada',
    levelLabel: 'Tingkat Waspada (Skor Risiko 50-74)',
    minRiskScore: 50,
    titleTemplate: '⚠️ Waspada: Mendekati Area Rawan {zone_name}',
    bodyTemplate: 'Anda berjarak {distance_m}m dari area dengan {incident_count} laporan insiden ({incident_type}). Tetap waspada dan hindari berhenti di bahu jalan sepi.',
    actionButtonText: 'Lihat Rute Alternatif',
    secondaryButtonText: 'Abaikan Peringatan',
    soundAlert: 'discrete_chime',
    vibrationPattern: 'normal',
    priority: 'Normal',
    accentColor: '#f59e0b',
  },
  {
    id: 'TMPL-BAHAYA',
    level: 'Bahaya',
    levelLabel: 'Tingkat Bahaya / Kritis (Skor Risiko 75-89)',
    minRiskScore: 75,
    titleTemplate: '🚨 PERINGATAN BAHAYA: Titik Rawan Begal Terdeteksi!',
    bodyTemplate: 'Radius {radius_m}m di depan ({zone_name}) berstatus Kritis ({risk_score}/100). Terdeteksi {incident_count} kasus begal/curas. Sistem menyarankan pengalihan rute segera!',
    actionButtonText: 'Alihkan ke Rute Teraman (+{detour_min} mnt)',
    secondaryButtonText: 'Tetap Lanjutkan (Bahaya)',
    soundAlert: 'urgent_siren',
    vibrationPattern: 'pulsed_alarm',
    priority: 'High',
    accentColor: '#ef4444',
  },
  {
    id: 'TMPL-DARURAT',
    level: 'Darurat',
    levelLabel: 'Level Darurat Live / SOS (Skor Risiko 90-100)',
    minRiskScore: 90,
    titleTemplate: '⚡ DARURAT LIVE: Insiden Kriminal Sedang Berlangsung!',
    bodyTemplate: 'Insiden kekerasan jalanan baru dilaporkan warga/polisi di {zone_name} (<10 mnt lalu). Segera putar balik atau tuju pos polisi/titik terang terdekat!',
    actionButtonText: 'Panggil Bantuan Darurat (110)',
    secondaryButtonText: 'Pandu ke Pos Polisi Terdekat',
    soundAlert: 'urgent_siren',
    vibrationPattern: 'continuous',
    priority: 'Emergency',
    accentColor: '#dc2626',
  },
];

export const mockZoneNotificationSchedules: ZoneNotificationSchedule[] = [
  {
    id: 'ZONE-SCHED-01',
    zoneName: 'Menteng & Tanah Abang',
    region: 'Jakarta Pusat',
    isCustomSchedule: false,
    activeStartTime: '00:00',
    activeEndTime: '04:59',
    is24HoursEmergencyActive: true,
    triggerRadiusMeters: 450,
    userCooldownMinutes: 30,
    isActive: true,
  },
  {
    id: 'ZONE-SCHED-02',
    zoneName: 'Casablanca, Tebet & Antasari',
    region: 'Jakarta Selatan',
    isCustomSchedule: true,
    activeStartTime: '23:00',
    activeEndTime: '05:00',
    is24HoursEmergencyActive: true,
    triggerRadiusMeters: 600,
    userCooldownMinutes: 20,
    isActive: true,
  },
  {
    id: 'ZONE-SCHED-03',
    zoneName: 'Jalur Kalimalang & Perbatasan Bekasi',
    region: 'Jakarta Timur - Bekasi',
    isCustomSchedule: true,
    activeStartTime: '22:30',
    activeEndTime: '05:30',
    is24HoursEmergencyActive: true,
    triggerRadiusMeters: 800,
    userCooldownMinutes: 15,
    isActive: true,
  },
  {
    id: 'ZONE-SCHED-04',
    zoneName: 'Margonda Raya & Akses UI',
    region: 'Kota Depok',
    isCustomSchedule: true,
    activeStartTime: '23:00',
    activeEndTime: '04:30',
    is24HoursEmergencyActive: true,
    triggerRadiusMeters: 500,
    userCooldownMinutes: 30,
    isActive: true,
  },
  {
    id: 'ZONE-SCHED-05',
    zoneName: 'Daan Mogot & Cengkareng Barat',
    region: 'Jakarta Barat',
    isCustomSchedule: false,
    activeStartTime: '00:00',
    activeEndTime: '04:59',
    is24HoursEmergencyActive: true,
    triggerRadiusMeters: 650,
    userCooldownMinutes: 25,
    isActive: true,
  },
  {
    id: 'ZONE-SCHED-06',
    zoneName: 'Cilincing & Pelabuhan Tanjung Priok',
    region: 'Jakarta Utara',
    isCustomSchedule: true,
    activeStartTime: '21:00',
    activeEndTime: '05:00',
    is24HoursEmergencyActive: true,
    triggerRadiusMeters: 750,
    userCooldownMinutes: 20,
    isActive: true,
  },
];

export const mockPushTestLogs: PushTestLog[] = [
  {
    id: 'PUSH-TEST-701',
    timestamp: '2026-09-17T21:10:00Z',
    targetIdentifier: 'Perangkat Uji QA-01 (+62 812-9900-1122)',
    level: 'Bahaya',
    renderedTitle: '🚨 PERINGATAN BAHAYA: Titik Rawan Begal Terdeteksi!',
    renderedBody: 'Radius 500m di depan (Casablanca, Tebet) berstatus Kritis (82/100). Terdeteksi 14 kasus begal/curas. Sistem menyarankan pengalihan rute segera!',
    status: 'Delivered',
    deliveryLatencyMs: 94,
    fcmMessageId: 'fcm_msg_0199aefb220',
  },
  {
    id: 'PUSH-TEST-702',
    timestamp: '2026-09-17T20:45:00Z',
    targetIdentifier: 'Device Simulator Web (+62 856-1122-3344)',
    level: 'Waspada',
    renderedTitle: '⚠️ Waspada: Mendekati Area Rawan Margonda Raya & Akses UI',
    renderedBody: 'Anda berjarak 350m dari area dengan 8 laporan insiden (Pelecehan Seksual). Tetap waspada dan hindari berhenti di bahu jalan sepi.',
    status: 'Delivered',
    deliveryLatencyMs: 112,
    fcmMessageId: 'fcm_msg_0199aeaa710',
  },
  {
    id: 'PUSH-TEST-703',
    timestamp: '2026-09-17T19:30:00Z',
    targetIdentifier: 'Token APNs iPhone 16 Pro (Admin QA)',
    level: 'Darurat',
    renderedTitle: '⚡ DARURAT LIVE: Insiden Kriminal Sedang Berlangsung!',
    renderedBody: 'Insiden kekerasan jalanan baru dilaporkan warga/polisi di Jalur Kalimalang (<10 mnt lalu). Segera putar balik atau tuju pos polisi/titik terang terdekat!',
    status: 'Delivered',
    deliveryLatencyMs: 78,
    fcmMessageId: 'fcm_msg_0199ae77199',
  },
];

// 12. SISTEM MONITORING & JOB QUEUE MOCK DATA
export const mockSystemJobs: SystemJob[] = [
  {
    id: 'JOB-DBSCAN-01',
    type: 'dbscan_clustering',
    title: 'DBSCAN Spatial Hotspot Clustering Engine',
    status: 'running',
    progressPct: 68,
    startedAt: '2026-09-17T21:30:10Z',
    triggeredBy: 'Scheduled Cron',
    recordsProcessed: 2410,
    memoryPeakMb: 820,
  },
  {
    id: 'JOB-RF-02',
    type: 'random_forest_training',
    title: 'Pelatihan Ulang Model Random Forest v2.4 (Feedback Augmented)',
    status: 'success',
    progressPct: 100,
    startedAt: '2026-09-17T20:00:00Z',
    completedAt: '2026-09-17T20:03:04Z',
    durationSeconds: 184,
    triggeredBy: 'Manual Superadmin',
    recordsProcessed: 18420,
    memoryPeakMb: 1420,
  },
  {
    id: 'JOB-SYNC-03',
    type: 'police_external_sync',
    title: 'Sinkronisasi Data Eksternal Bareskrim Pusiknas',
    status: 'success',
    progressPct: 100,
    startedAt: '2026-09-17T21:15:00Z',
    completedAt: '2026-09-17T21:15:02Z',
    durationSeconds: 2,
    triggeredBy: 'Scheduled Cron',
    recordsProcessed: 18,
    memoryPeakMb: 210,
  },
  {
    id: 'JOB-CACHE-04',
    type: 'route_cache_purge',
    title: 'Purging Cache Graf Rute A* & Invalidation',
    status: 'success',
    progressPct: 100,
    startedAt: '2026-09-17T18:00:00Z',
    completedAt: '2026-09-17T18:00:08Z',
    durationSeconds: 8,
    triggeredBy: 'Manual Superadmin',
    recordsProcessed: 54000,
    memoryPeakMb: 450,
  },
  {
    id: 'JOB-DBSCAN-FAIL',
    type: 'dbscan_clustering',
    title: 'DBSCAN Kalibrasi Epsilon 250m Jabodetabek Eksperimental',
    status: 'failed',
    progressPct: 45,
    startedAt: '2026-09-17T14:20:00Z',
    completedAt: '2026-09-17T14:21:15Z',
    durationSeconds: 75,
    triggeredBy: 'Manual Superadmin',
    errorMessage: 'OutOfMemoryError: Pairwise geodesic distance matrix computation exceeded allocation limit (4096 MB)',
    memoryPeakMb: 4096,
  },
  {
    id: 'JOB-OSM-05',
    type: 'osm_road_graph_sync',
    title: 'Sinkronisasi Topologi Jalan OpenStreetMap DKI Jakarta',
    status: 'queued',
    progressPct: 0,
    startedAt: '2026-09-17T22:00:00Z',
    triggeredBy: 'Scheduled Cron',
  },
];

export const mockAStarMetrics: AStarPerformanceMetrics = {
  avgResponseTimeMs: 142,
  p95ResponseTimeMs: 290,
  requestsPerMinute: 428,
  peakRpmToday: 890,
  errorRatePct: 0.14,
  totalRoutesCalculatedToday: 38450,
  activeGraphNodes: 142800,
  activeGraphEdges: 329400,
  cacheHitRatioPct: 78.4,
};

// 13. FEEDBACK LOOP RUTE MOCK DATA
export const mockRouteFeedbacks: RouteFeedbackItem[] = [
  {
    id: 'FDB-2026-001',
    routeSearchId: 'SRCH-88192',
    originName: 'Stasiun Tebet',
    destinationName: 'Mega Kuningan, Jl. Prof. Dr. Satrio',
    chosenRouteType: 'safe',
    predictedRiskScore: 22,
    userRating: 1,
    safetyPerception: 'Berbahaya',
    comment: 'Katanya rute aman tapi pas lewat bawah flyover Casablanca sangat gelap gulita dan ada 3 motor mencurigakan nongkrong di bahu jalan!',
    hasDiscrepancy: true,
    status: 'Flagged for Retrain',
    trainingInclusionStatus: 'Queued for Next Retrain',
    reportedAt: '2026-09-17T21:10:00Z',
    userName: 'Dimas Kurniawan',
    userTrustScore: 92,
  },
  {
    id: 'FDB-2026-002',
    routeSearchId: 'SRCH-88145',
    originName: 'Cipinang Muara',
    destinationName: 'Kalimalang Caman Bekasi',
    chosenRouteType: 'safe',
    predictedRiskScore: 28,
    userRating: 2,
    safetyPerception: 'Ragu-ragu',
    comment: 'Masih banyak lampu PJU mati di sisi kiri jalan inspeksi, padahal sistem kasih label Aman.',
    hasDiscrepancy: true,
    status: 'Flagged for Retrain',
    trainingInclusionStatus: 'Queued for Next Retrain',
    reportedAt: '2026-09-17T20:30:00Z',
    userName: 'Rangga Putra',
    userTrustScore: 86,
  },
  {
    id: 'FDB-2026-003',
    routeSearchId: 'SRCH-88090',
    originName: 'Monas Barat',
    destinationName: 'Bundaran Senayan',
    chosenRouteType: 'fastest',
    predictedRiskScore: 15,
    userRating: 5,
    safetyPerception: 'Sangat Aman',
    comment: 'Rute utama sangat terang dan banyak pos polisi berjaga. Akurasi mantap!',
    hasDiscrepancy: false,
    status: 'Investigated',
    trainingInclusionStatus: 'Trained',
    reportedAt: '2026-09-17T19:45:00Z',
    userName: 'Anisa Rahma',
    userTrustScore: 95,
  },
  {
    id: 'FDB-2026-004',
    routeSearchId: 'SRCH-87980',
    originName: 'Margonda Raya',
    destinationName: 'Kukusan Kelurahan UI Depok',
    chosenRouteType: 'safe',
    predictedRiskScore: 24,
    userRating: 1,
    safetyPerception: 'Kritis / Ada Kejahatan',
    comment: 'Ada kejadian penjambretan tas motor tepat sebelum gang masuk Kukusan jam 01.30 pagi tadi. Tolong naikkan level bahaya area ini!',
    hasDiscrepancy: true,
    status: 'Flagged for Retrain',
    trainingInclusionStatus: 'Queued for Next Retrain',
    reportedAt: '2026-09-17T18:20:00Z',
    userName: 'Bambang Irawan',
    userTrustScore: 90,
  },
  {
    id: 'FDB-2026-005',
    routeSearchId: 'SRCH-87910',
    originName: 'Terminal Kalideres',
    destinationName: 'Mall Taman Anggrek',
    chosenRouteType: 'fastest',
    predictedRiskScore: 48,
    userRating: 3,
    safetyPerception: 'Cukup Aman',
    comment: 'Rute Daan Mogot agak ramai truk kontainer tapi tidak ada begal.',
    hasDiscrepancy: false,
    status: 'Pending',
    trainingInclusionStatus: 'Not Included',
    reportedAt: '2026-09-17T17:15:00Z',
    userName: 'Hendra Setiawan',
    userTrustScore: 78,
  },
  {
    id: 'FDB-2026-006',
    routeSearchId: 'SRCH-87850',
    originName: 'Stasiun Manggarai',
    destinationName: 'Tebet Eco Park',
    chosenRouteType: 'safe',
    predictedRiskScore: 18,
    userRating: 5,
    safetyPerception: 'Sangat Aman',
    comment: 'Diarahkan lewat jalan besar yang ramai, lebih tenang berkendara.',
    hasDiscrepancy: false,
    status: 'Investigated',
    trainingInclusionStatus: 'Trained',
    reportedAt: '2026-09-17T16:00:00Z',
    userName: 'Siti Sarah',
    userTrustScore: 94,
  },
];

// 14. DATA EXPORT & KEPATUHAN PRIVASI MOCK DATA
export const mockDataRetentionPolicy: DataRetentionPolicy = {
  anonymizeReporterAfterMonths: 6,
  purgeRawTelemetryDays: 90,
  aggregatePoliceExportRetentionYears: 3,
  lastRetentionRun: '2026-09-17T02:00:00Z',
  autoAnonymizeEnabled: true,
};

export const mockSensitiveDataLogs: SensitiveDataAccessLog[] = [
  {
    id: 'LOG-EXP-501',
    adminName: 'Budi Santoso',
    adminEmail: 'superadmin@jalananman.id',
    role: 'Superadmin',
    actionType: 'Export Agregat Kepolisian',
    targetScope: 'Titik Rawan Begal & Hotspot DBSCAN Jabodetabek (Q3 2026)',
    justification: 'Surat Permintaan Data Ditreskrimum Polda Metro Jaya No. B/102/IX/2026',
    ipAddress: '103.247.12.88',
    timestamp: '2026-09-17T14:15:00Z',
    recordsCount: 1420,
    status: 'Approved',
  },
  {
    id: 'LOG-EXP-502',
    adminName: 'Siti Aminah',
    adminEmail: 'siti.moderator@jalananman.id',
    role: 'Moderator',
    actionType: 'Lihat Data Mentah PII',
    targetScope: 'Foto Korban & Nomor Polisi Laporan INC-2023-001',
    justification: 'Verifikasi identitas korban untuk redaksi sensor peta publik',
    ipAddress: '182.253.11.45',
    timestamp: '2026-09-17T16:20:00Z',
    recordsCount: 1,
    status: 'Logged',
  },
  {
    id: 'LOG-EXP-503',
    adminName: 'Budi Santoso',
    adminEmail: 'superadmin@jalananman.id',
    role: 'Superadmin',
    actionType: 'Export Laporan CSV Pemkot',
    targetScope: 'Rekapitulasi PJU Padam & Jalan Berlubang untuk Dinas Bina Marga DKI',
    justification: 'Koordinasi perbaikan fasilitas jalan dengan Pemprov DKI Jakarta',
    ipAddress: '103.247.12.88',
    timestamp: '2026-09-16T11:00:00Z',
    recordsCount: 384,
    status: 'Approved',
  },
  {
    id: 'LOG-EXP-504',
    adminName: 'Budi Santoso',
    adminEmail: 'superadmin@jalananman.id',
    role: 'Superadmin',
    actionType: 'Audit Data Consent',
    targetScope: 'Pengecekan Kepatuhan Opt-In Pengguna UU PDP & GDPR',
    justification: 'Audit Kepatuhan Privasi Kuartal III Tahun 2026',
    ipAddress: '103.247.12.88',
    timestamp: '2026-09-15T09:30:00Z',
    recordsCount: 142500,
    status: 'Approved',
  },
];

export const mockUserConsentMetrics: UserConsentMetrics = {
  totalUsers: 142500,
  clusteringOptInPct: 98.4,
  aiTrainingOptInPct: 95.1,
  telemetryOptInPct: 89.6,
  gdprErasureRequestsPending: 2,
  lastConsentAuditDate: '2026-09-15',
};





